In [491]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
import pickle
from datetime import datetime

In [492]:
data = pd.read_excel("Data/dataset_comp_1222_without_ceg_ogn.xlsx")

In [493]:
data.loc[data['SYMBOL'] == 'PARA']

,Unnamed: 0,NAME,TYPE,SYMBOL,GICS Sector,ffnosh last day dic 22,Price last day dic 22,Scope 1,Scope 2,Scope 3,...,Sector_Information Technology,Sector_Materials,Sector_Real Estate,Sector_Utilities,Scope 1 Imputed,Scope 2 Imputed,Scope 3 Imputed,weight_in_sector,float_mcap,rank_in_sector
447,447,PARAMOUNT GLOBAL B,32480Q,PARA,Communication Services,482066,16.77,181218.0,173309.0,2361795.0,...,0,0,0,0,NaN,NaN,NaN,0.003462,8084246.82,18

## 2023–mid 2025 backtesting

In [494]:
# # Define the tickers and date range
# tickers = list(data['SYMBOL'].values) # Add more tickers as needed
# start_date = "2022-12-30"
# end_date = "2025-07-01"

# # Download the data
# yahoo_data = yf.download(tickers, start=start_date, end=end_date, group_by='ticker', auto_adjust=False, progress=False)

# # Extract adjusted close prices
# adj_close_bt = pd.DataFrame()

# # If only one ticker, yfinance doesn't use a multi-indexed DataFrame, handle accordingly
# if len(tickers) == 1:
#     adj_close_bt[tickers[0]] = yahoo_data['Adj Close']
# else:
#     for ticker in tickers:
#         try:
#             adj_close_bt[ticker] = yahoo_data[ticker]['Adj Close']
#         except KeyError:
#             print(f"No data found for {ticker}.")

# # Display the result
# print(adj_close_bt.head())

In [495]:
# #print(data.loc[data['SYMBOL'] == 'BF.B'])
# # Define the tickers and date range
# tickers = ['BF-B'] # Add more tickers as needed
# start_date = "2022-12-30"
# end_date = "2025-07-01"

# # Download the data
# data_bfb = yf.download(tickers, start=start_date, end=end_date, group_by='ticker', auto_adjust=False, progress=False)

# # Extract adjusted close prices
# adj_close_bfb = pd.DataFrame()

# # If only one ticker, yfinance doesn't use a multi-indexed DataFrame, handle accordingly
# if len(tickers) == 1:
#     adj_close_bfb[tickers[0]] = data_bfb['BF-B']['Adj Close']
# else:
#     for ticker in tickers:
#         try:
#             adj_close_bfb[ticker] = data_bfb[ticker]['Adj Close']
#         except KeyError:
#             print(f"No data found for {ticker}.")

# # Display the result
# #print(adj_close_bfb.head())
# adj_close_bt['BF.B'] = adj_close_bfb.values

Redownload failed downloads:

In [496]:
# # Define the tickers and date range
# tickers = ['HUM'] # Add more tickers as needed
# start_date = "2022-12-30"
# end_date = "2025-07-01"

# # Download the data
# data_redownload = yf.download(tickers, start=start_date, end=end_date, group_by='ticker', auto_adjust=False, progress=False)

# # Extract adjusted close prices
# adj_close_redownload = pd.DataFrame()

# # If only one ticker, yfinance doesn't use a multi-indexed DataFrame, handle accordingly
# if len(tickers) == 1:
#     adj_close_redownload[tickers[0]] = data_redownload[tickers[0]]['Adj Close']
# else:
#     for ticker in tickers:
#         try:
#             adj_close_redownload[ticker] = data_redownload[ticker]['Adj Close']
#         except KeyError:
#             print(f"No data found for {ticker}.")

# # Display the result
# adj_close_bt[tickers] = adj_close_redownload.values

In [497]:
# adj_close_bt.to_excel("Data/adj_price_yahoo_comp_1222_2325.xlsx")

In [498]:
adj_close_bt = pd.read_excel("Data/adj_price_yahoo_comp_1222_2325.xlsx")
adj_close_bt.index = adj_close_bt.Date
adj_close_bt.drop(columns='Date', inplace=True)

In [499]:
nan_columns = adj_close_bt.columns[adj_close_bt.isna().any()]
print(nan_columns)

Index(['DISH', 'ATVI', 'PXD', 'SIVBQ', 'MRO', 'SBNY', 'DFS', 'CTLT', 'WRK'], dtype='object')

In [500]:
ffnosh_historical = pd.read_excel('Data/price_div_comp_1222_0323.xlsm', sheet_name='FFNOSH', header = 4)
ffnosh_historical.columns =ffnosh_historical.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
ffnosh_historical = ffnosh_historical.iloc[:-1]

In [501]:
ffnosh_historical.head()

,Code,891399,916328,545101,906187,936365,749382,891631,905271,921794,...,9801CK,9174A0,905277,916091,871997,902335,512785,9373MH,699786,68470X
0,2022-12-30,9249366,1654707,502652,853138,1207610,475800,134531,208751,125305,...,1174930,809091,959481,239392,5240412,291410,756604,492561,101966,117215
1,2023-01-02,9254628,1649080,502652,853138,1207610,451910,135848,208751,125305,...,1174930,895770,960063,239257,5206418,291410,756604,492161,101966,117215
2,2023-01-03,9254628,1649080,502652,853138,1207610,451910,135848,208751,125305,...,1174930,895770,960063,239257,5206418,291410,756604,492161,101966,117215
3,2023-01-04,9254628,1649080,502652,853138,1207610,451910,135848,208751,125305,...,1174930,895770,960063,239257,5206418,291410,756604,492161,101966,117215
4,2023-01-05,9254628,1649080,502652,853138,1207610,451910,135848,208751,125305,...,1174930,895770,960063,239257,5206418,291410,756604,492161,101966,117215

In [502]:
price_historical = pd.read_excel('Data/price_div_comp_1222_0323.xlsm', sheet_name='CLOSE PRICE', header = 4)
price_historical.columns = price_historical.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
price_historical = price_historical.iloc[:-1]

div_rate_historical = pd.read_excel('Data/price_div_comp_1222_0323.xlsm', sheet_name='DIV RATE', header = 4)
div_rate_historical.columns = div_rate_historical.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
div_rate_historical = div_rate_historical.iloc[:-1]

div_date_historical = pd.read_excel('Data/price_div_comp_1222_0323.xlsm', sheet_name='DIV DATE', header = 4)
div_date_historical.columns = div_date_historical.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
div_date_historical = div_date_historical.iloc[:-1]

ffnosh_historical = pd.read_excel('Data/price_div_comp_1222_0323.xlsm', sheet_name='FFNOSH', header = 4)
ffnosh_historical.columns =ffnosh_historical.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
ffnosh_historical = ffnosh_historical.iloc[:-1]


div_date_historical.columns = price_historical.columns
div_rate_historical.columns = price_historical.columns
ffnosh_historical.columns = price_historical.columns

price_historical.index = price_historical.Code
div_rate_historical.index = div_rate_historical.Code
div_date_historical.index = div_date_historical.Code
ffnosh_historical.index = ffnosh_historical.Code

price_historical = price_historical.iloc[:, 1:]
div_rate = div_rate_historical.iloc[:, 1:]
div_date_historical = div_date_historical.iloc[:, 1:]
ffnosh_historical = ffnosh_historical.iloc[:, 1:]

# --- Step 1: Calculate adjustment factors
adj_factors = pd.DataFrame(1.0, index=price_historical.index, columns=price_historical.columns)

for company in price_historical.columns:
    for i in range(1, len(price_historical)):
        date = price_historical.index[i]
        prev_date = price_historical.index[i - 1]

        # If ex-dividend happens on this day
        if pd.notna(div_date_historical.at[date, company]):
            div = div_rate.at[date, company]
            price_prev = price_historical.at[prev_date, company]
            if price_prev and price_prev != 0:
                factor = (price_prev - div) / price_prev
                adj_factors.at[date, company] = factor

# --- Step 2: Calculate cumulative adjustment factors in reverse (like Yahoo)
cum_factors = adj_factors.iloc[::-1].cumprod().iloc[::-1]

# --- Step 3: Build adjusted prices
adjusted_prices_calculated = price_historical * cum_factors

#print(data.loc[data['SYMBOL'] == 'WRK', 'NAME'])
#print(div_rate['96699P'].unique())
#print(price_historical['96699P'])
#print(adjusted_prices_calculated['96699P'])
adj_close_bt['WRK'] = adjusted_prices_calculated.loc[adj_close_bt.index, '96699P'].values

#print(data.loc[data['SYMBOL'] == 'CTLT', 'NAME'])
#print(div_rate['8866F3'].unique())
#print(price_historical['8866F3'])
#print(adjusted_prices_calculated['8866F3'])
adj_close_bt['CTLT'] = adjusted_prices_calculated.loc[adj_close_bt.index, ['8866F3']].values

#print(data.loc[data['SYMBOL'] == 'MRO', 'NAME'])
#print(div_rate['544682'].unique())
#print(price_historical['544682'])
#print(adjusted_prices_calculated['544682'])
adj_close_bt['MRO'] = adjusted_prices_calculated.loc[adj_close_bt.index, '544682'].values

#print(data.loc[data['SYMBOL'] == 'PXD', 'NAME'])
#print(div_rate['895705'].unique())
#print(price_historical['895705'])
adj_close_bt['PXD'] = adjusted_prices_calculated.loc[adj_close_bt.index, '895705'].values

#print(data.loc[data['SYMBOL'] == 'SBNY', ['NAME','TYPE']])
#print(div_rate['28709C'].unique())
#print(price_historical['28709C'])
adj_close_bt['SBNY'] = adjusted_prices_calculated.loc[adj_close_bt.index, '28709C'].values

#print(data.loc[data['SYMBOL'] == 'ATVI', ['NAME','TYPE']])
#print(div_rate['312367'].unique())
#print(price_historical['312367'])
adj_close_bt['ATVI'] = adjusted_prices_calculated.loc[adj_close_bt.index, '312367'].values

#print(data.loc[data['SYMBOL'] == 'DISH', ['NAME','TYPE']])
#print(div_rate['135448'].unique())
#print(price_historical['135448'])
adj_close_bt['DISH'] = adjusted_prices_calculated.loc[adj_close_bt.index, '135448'].values

#print(data.loc[data['SYMBOL'] == 'SIVBQ', ['NAME','TYPE']])
#print(div_rate['518628'].unique())
#print(price_historical['518628'])
adj_close_bt['SIVBQ'] = adjusted_prices_calculated.loc[adj_close_bt.index, '518628'].values

print(div_rate['50642F'].unique())
print(price_historical['50642F'])
adj_close_bt['DFS'] = adjusted_prices_calculated.loc[adj_close_bt.index, '50642F'].values

[nan 0.6 0.7]
Code
2022-12-30     97.83
2023-01-02     97.83
2023-01-03     96.99
2023-01-04    101.27
2023-01-05     99.55
               ...
2025-06-24    200.05
2025-06-25    200.05
2025-06-26    200.05
2025-06-27    200.05
2025-06-30    200.05
Name: 50642F, Length: 652, dtype: float64

In [503]:
nan_columns = adj_close_bt.columns[adj_close_bt.isna().any()]
print(nan_columns)

Index([], dtype='object')

In [504]:
adj_close_bt.isna().any().any()

False

### Market-cap–weighted index (S&P 500 approximation):

Start from Dec 2022 composition, but instead of freezing weights, I recalculate weights each day 

-> This way, weights “evolve naturally with returns” 

-> This mimics how the real S&P 500 works (ignoring reconstitutions)

vs 

 Buy-and-hold portfolio 

You fix the weights at Dec 2022 values (e.g., Apple 7%, Microsoft 6%).

You do not update them after that.

The portfolio return is just the weighted sum of stock returns with those fixed weights.

Over time, it drifts away from being market-cap proportional.

👉 Analogy: If you buy the S&P 500 in Dec 2022 and literally never rebalance, you’re doing buy-and-hold.

In [505]:
price_historical = pd.read_excel('Data/price_div_comp_1222_0323.xlsm', sheet_name='CLOSE PRICE', header = 4)
price_historical.columns = price_historical.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
price_historical = price_historical.iloc[:-1]

div_rate_historical = pd.read_excel('Data/price_div_comp_1222_0323.xlsm', sheet_name='DIV RATE', header = 4)
div_rate_historical.columns = div_rate_historical.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
div_rate_historical = div_rate_historical.iloc[:-1]

div_date_historical = pd.read_excel('Data/price_div_comp_1222_0323.xlsm', sheet_name='DIV DATE', header = 4)
div_date_historical.columns = div_date_historical.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
div_date_historical = div_date_historical.iloc[:-1]

ffnosh_historical = pd.read_excel('Data/price_div_comp_1222_0323.xlsm', sheet_name='FFNOSH', header = 4)
ffnosh_historical.columns =ffnosh_historical.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
ffnosh_historical = ffnosh_historical.iloc[:-1]


div_date_historical.columns = price_historical.columns
div_rate_historical.columns = price_historical.columns
ffnosh_historical.columns = price_historical.columns

price_historical.index = price_historical.Code
div_rate_historical.index = div_rate_historical.Code
div_date_historical.index = div_date_historical.Code
ffnosh_historical.index = ffnosh_historical.Code

price_historical = price_historical.iloc[:, 1:]
div_rate = div_rate_historical.iloc[:, 1:]
div_date_historical = div_date_historical.iloc[:, 1:]
ffnosh_historical = ffnosh_historical.iloc[:, 1:]

type_lseg = pd.read_excel("Data/symbol_comp_1222.xlsm", sheet_name="SYMBOL", dtype=str).iloc[0].values[1:]
symbol_lseg = pd.read_excel("Data/symbol_comp_1222.xlsm", sheet_name="SYMBOL", dtype=str, header=2)
symbol_lseg = symbol_lseg.iloc[:1].transpose().reset_index().rename(columns= {"index": "NAME", 0: "SYMBOL"}).iloc[1:]
symbol_lseg['TYPE'] = type_lseg

symbol_type_matches  = symbol_lseg.set_index("TYPE")["SYMBOL"].to_dict()

price_historical_renamed = price_historical.rename(columns=symbol_type_matches)
ffnosh_historical_renamed = ffnosh_historical.rename(columns=symbol_type_matches)

exclude_stocks = ['CEG', 'OGN']
price_historical = price_historical_renamed.drop(columns=exclude_stocks)
ffnosh_historical = ffnosh_historical_renamed.drop(columns=exclude_stocks)

# change symbol from BRK.A to BRK-B:
price_historical.rename(columns={'BRK.A':'BRK-B'}, inplace=True)
ffnosh_historical.rename(columns={'BRK.A':'BRK-B'}, inplace=True)

price_historical.index = pd.to_datetime(price_historical.index)
ffnosh_historical.index = pd.to_datetime(ffnosh_historical.index)

# Example duplicate map
duplicate_map = {
    "GOOG": "GOOGL",  # aggregate under GOOG
    "FOX": "FOXA",    # aggregate under FOXA
    "NWS": "NWSA"     # aggregate under NWSA
}

# --- Step 1: Align indexes ---
price_historical.index = pd.to_datetime(price_historical.index)
ffnosh_historical.index = pd.to_datetime(ffnosh_historical.index)

# --- Step 2: Apply duplicate mapping ---
price_historical = price_historical.rename(columns=duplicate_map)
ffnosh_historical = ffnosh_historical.rename(columns=duplicate_map)

# After renaming, duplicates will exist → group and aggregate
def aggregate_duplicates(price_df, ffnosh_df):
    # Weighted price = Σ(price * shares) / Σ(shares)
    weighted_price = (price_df * ffnosh_df).groupby(axis=1, level=0).sum() / ffnosh_df.groupby(axis=1, level=0).sum()
    total_ffnosh = ffnosh_df.groupby(axis=1, level=0).sum()
    return weighted_price, total_ffnosh


price_agg, ffnosh_agg = aggregate_duplicates(price_historical, ffnosh_historical)
day = "2023-01-04"
goog_price = price_historical.loc[day, ["GOOGL", "GOOGL"]]
goog_shares = ffnosh_historical.loc[day, ["GOOGL", "GOOGL"]]

# Manual weighted price
manual = (goog_price * goog_shares).sum() / goog_shares.sum()
print("Aggregated price (GOOG):", price_agg.loc[day, "GOOGL"])
print("Manual:", manual)

# --- Step 3: Float-adjusted market cap ---
float_mcap = price_agg * ffnosh_agg


# --- Step 4: Add sector info ---
sector_map = data.set_index("SYMBOL")["GICS Sector"].to_dict()
sector_map_series = pd.Series(sector_map)

# Make sure columns align
float_mcap = float_mcap.loc[:, sector_map_series.index]

# --- Step 5: Compute sector-level weights daily ---
sector_weights = {}
for sector in sector_map_series.unique():
    tickers = sector_map_series[sector_map_series == sector].index
    sector_mcap = float_mcap[tickers].sum(axis=1)
    sector_weights[sector] = float_mcap[tickers].div(sector_mcap, axis=0)

# Example: weights for Tech sector
print(sector_weights["Information Technology"].head())

Aggregated price (GOOG): 88.3738470266926
Manual: 88.3738470266926
                 IBM       AMD      ADBE       ADI      ANSS      AAPL  \
Code
2022-12-30  0.016959  0.011036  0.022591  0.012414  0.002806  0.282518
2023-01-02  0.016986  0.011053  0.021492  0.012434  0.002811  0.282950
2023-01-03  0.017275  0.011060  0.021781  0.012466  0.002811  0.275716
2023-01-04  0.017417  0.011179  0.022089  0.012741  0.002864  0.278783
2023-01-05  0.017594  0.011001  0.021692  0.012519  0.002788  0.281568

                AMAT      ADSK      VRSN       APH  ...      AVGO       GEN  \
Code                                                ...
2022-12-30  0.010989  0.005796  0.002658  0.005472  ...  0.026545  0.001508
2023-01-02  0.011020  0.005806  0.002662  0.005475  ...  0.026588  0.001500
2023-01-03  0.011081  0.005823  0.002649  0.005561  ...  0.026643  0.001532
2023-01-04  0.011386  0.005916  0.002699  0.005648  ...  0.026990  0.001551
2023-01-05  0.011460  0.005850  0.002681  0.005704  ...  0.027295  0.001528

                 STX      ANET      KEYS      QRVO      SEDG       HPE  \
Code
2022-12-30  0.001473  0.004447  0.004117  0.001247  0.002243  0.002765
2023-01-02  0.001476  0.004455  0.004122  0.001246  0.002247  0.002771
2023-01-03  0.001473  0.004493  0.004169  0.001241  0.002292  0.002823
2023-01-04  0.001491  0.004234  0.004162  0.001268  0.002335  0.002889
2023-01-05  0.001552  0.004157  0.004208  0.001284  0.002270  0.002954

                 HPQ       DXC
Code
2022-12-30  0.003637  0.000895
2023-01-02  0.003646  0.000896
2023-01-03  0.003674  0.000947
2023-01-04  0.003741  0.000965
2023-01-05  0.003818  0.000967

[5 rows x 63 columns]

/var/folders/n9/cy4s67js3v58hhczg4lxj5jr0000gq/T/ipykernel_69957/1828827138.py:71: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  weighted_price = (price_df * ffnosh_df).groupby(axis=1, level=0).sum() / ffnosh_df.groupby(axis=1, level=0).sum()
/var/folders/n9/cy4s67js3v58hhczg4lxj5jr0000gq/T/ipykernel_69957/1828827138.py:71: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  weighted_price = (price_df * ffnosh_df).groupby(axis=1, level=0).sum() / ffnosh_df.groupby(axis=1, level=0).sum()
/var/folders/n9/cy4s67js3v58hhczg4lxj5jr0000gq/T/ipykernel_69957/1828827138.py:72: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  total_ffnosh = ffnosh_df.groupby(axis=1, level=0).sum()

I have the consitutents composition of dec 2022, so I want to remove the OGN and CEG, and have the weighted price for the duplicates companies (GOOGL, NWSA, FOX):

In [506]:
day = "2023-01-03"
print("AMZN test:")
print("Price:", price_agg.loc[day, "AMZN"])
print("Shares:", ffnosh_agg.loc[day, "AMZN"])
print("Market Cap:", float_mcap.loc[day, "AMZN"])
print("Expected:", price_agg.loc[day, "AMZN"] * ffnosh_agg.loc[day, "AMZN"])

AMZN test:
Price: 85.82
Shares: 9254628
Market Cap: 794232174.9599999
Expected: 794232174.9599999

In [507]:
for sector, w_df in sector_weights.items():
    assert all(abs(w_df.sum(axis=1) - 1) < 1e-8), f"Sector {sector} not summing to 1"

In [508]:
all_weights = pd.concat(sector_weights.values(), axis=1)
print(all_weights.sum(axis=1).head())

Code
2022-12-30    11.0
2023-01-02    11.0
2023-01-03    11.0
2023-01-04    11.0
2023-01-05    11.0
dtype: float64

## Calculate historical returns in the period 2023-2025:

In [509]:
def calculate_monthly_returns(df):
    # Clean data: replace zeros and drop fully NaN rows
    df = df.replace(0.0, np.nan).dropna(how="all")
    
    # Resample to monthly frequency using last available price in each month
    df_monthly = df.resample("ME").last()
    
    # Calculate monthly simple returns (percentage change)
    df_returns = df_monthly.pct_change().dropna()
    
    # Optional: set index to mid-month for visualization consistency
    df_returns.index = df_returns.index.map(lambda x: x.replace(day=15))
    
    return df_returns

In [510]:
monthly_returns_23_25 = calculate_monthly_returns(adj_close_bt)

In [511]:
daily_returns_23_25 = adj_close_bt.pct_change().dropna()

## Realized TEs (with 2% TE Constraint) in the period 2023-2025:

In [512]:

with open('Data/optimal_portfolios_1222_without_ceg_ogn_minimum_weight.pkl', 'rb') as f:
    optimal_portfolios_shrink = pickle.load(f)

In [513]:
def compute_buy_and_hold_returns(returns_df, weights, stock_labels):
    """
    Compute buy-and-hold (non-rebalanced) portfolio returns.
    
    Args:
        returns_df: DataFrame with stock returns (monthly), index = date, columns = tickers
        weights: np.array of initial weights (must match stock_labels)
        stock_labels: list or Index of tickers in this sector

    Returns:
        Series of portfolio returns over time (monthly)
    """
    # Subset return data for the sector
    sector_returns = returns_df[stock_labels]
    
    # Compute cumulative returns per stock
    cumulative_returns = (1 + sector_returns).cumprod()
    
    # Multiply by initial weights
    weighted_growth = cumulative_returns.multiply(weights, axis=1)
    
    # Total portfolio value each month
    portfolio_value = weighted_growth.sum(axis=1)
    
    # Convert to monthly portfolio returns
    portfolio_returns = portfolio_value.pct_change().dropna()

    return portfolio_returns

def compute_fixed_weight_returns(returns_df, weights, stock_labels):
    """
    Compute fixed-weight portfolio returns (decarbonised portfolio).
    
    Args:
        returns_df: DataFrame of monthly returns
        weights: np.array of optimised weights
        stock_labels: list or Index of stock tickers

    Returns:
        Series of portfolio returns over time
    """
    sector_returns = returns_df[stock_labels]
    portfolio_returns = sector_returns.dot(weights)
    return portfolio_returns

def compute_evolving_weight_returns(returns_df, daily_weights, stock_labels):
    """
    Compute portfolio returns with daily evolving (market-cap adjusted) weights.
    
    Args:
        returns_df: DataFrame of daily (or monthly) stock returns, index = dates, columns = tickers
        daily_weights: DataFrame of daily weights, index = dates, columns = tickers
        stock_labels: list of tickers in this sector
    
    Returns:
        Series of portfolio returns (aligned with returns_df index).
    """
    # Subset both to sector tickers
    sector_returns = returns_df[stock_labels]
    sector_weights = daily_weights[stock_labels]
    
    # Align on dates
    sector_returns, sector_weights = sector_returns.align(sector_weights, axis=0, join="inner")

    # Compute portfolio return each day: sum of (weights × returns)
    portfolio_returns = (sector_returns * sector_weights).sum(axis=1)
    
    return portfolio_returns

In [514]:
benchmark_returns = {}
for sector, data in sector_weights.items():
    tickers = data.columns     # stock labels for the sector
    
    # Compute sector-level buy-and-hold benchmark returns
    sector_returns = compute_evolving_weight_returns(
        daily_returns_23_25,
        data,
        stock_labels=tickers
    )
    
    benchmark_returns[sector] = sector_returns

benchmark_returns_df = pd.DataFrame(benchmark_returns)

In [515]:
decarb_sector_returns = {}

for sector, data in optimal_portfolios_shrink.items():
    w_opt = data['w_opt']
    tickers = data['stock_labels']
    
    sector_returns = compute_fixed_weight_returns(
        daily_returns_23_25,
        weights=w_opt,
        stock_labels=tickers
    )
    
    decarb_sector_returns[sector] = sector_returns

In [516]:
decarb_sector_returns['Consumer Discretionary']

Date
2023-01-03   -0.006673
2023-01-04    0.015674
2023-01-05   -0.010607
2023-01-06    0.024913
2023-01-09    0.007391
                ...
2025-06-24    0.005514
2025-06-25   -0.010933
2025-06-26    0.009069
2025-06-27    0.019895
2025-06-30   -0.005817
Length: 624, dtype: float64

In [517]:
benchmark_returns['Consumer Discretionary']

2023-01-03   -0.004897
2023-01-04    0.015087
2023-01-05   -0.010721
2023-01-06    0.024150
2023-01-09    0.008115
                ...
2025-06-24    0.007156
2025-06-25   -0.011090
2025-06-26    0.011677
2025-06-27    0.018631
2025-06-30   -0.009346
Length: 624, dtype: float64

EVOLVING WEIGHT RETURNS:

In [518]:
import numpy as np
import pandas as pd

sector_tracking_errors_6m = {}
sector_tracking_errors_avg = {}

# Approximate number of trading days in 6 months
window_size = 126  

for sector in decarb_sector_returns.keys():
    r_d = decarb_sector_returns[sector]  # optimized portfolio
    r_b = benchmark_returns[sector]      # benchmark portfolio
    
    # Align on dates
    common_index = r_d.index.intersection(r_b.index)
    r_d = r_d.loc[common_index]
    r_b = r_b.loc[common_index]
    
    # Active daily returns
    active_returns = r_d - r_b
    
    # Rolling 6M TE (annualized)
    rolling_te = (
        active_returns.rolling(window_size)
        .std()
        .dropna()
        * np.sqrt(252)   # annualize from daily std
    )
    
    # Store results
    sector_tracking_errors_6m[sector] = rolling_te
    sector_tracking_errors_avg[sector] = rolling_te.mean()

# Convert to DataFrame for inspection
te_df = pd.DataFrame(sector_tracking_errors_avg, index=["Avg_6M_TE"]).T
print(te_df.sort_values("Avg_6M_TE", ascending=False))

                        Avg_6M_TE
Information Technology   0.074950
Financials               0.068392
Communication Services   0.051950
Consumer Discretionary   0.046404
Health Care              0.044231
Consumer Staples         0.036653
Materials                0.036454
Industrials              0.033731
Real Estate              0.031985
Utilities                0.024941
Energy                   0.022847

In [519]:
import numpy as np
import pandas as pd

sector_te_specific = {}

for sector in decarb_sector_returns.keys():
    r_d = decarb_sector_returns[sector]  # optimized portfolio
    r_b = benchmark_returns[sector]      # benchmark portfolio

    # Align dates
    common_index = r_d.index.intersection(r_b.index)
    r_d = r_d.loc[common_index]
    r_b = r_b.loc[common_index]

    # Active daily returns
    active_returns = r_d - r_b

    # --- 3M window ---
    first_3m = active_returns.loc["2023-01-01":"2023-03-31"]
    te_3m = first_3m.std() * np.sqrt(252) if not first_3m.empty else np.nan

    # --- 6M window ---
    first_6m = active_returns.loc["2023-01-01":"2023-06-30"]
    te_6m = first_6m.std() * np.sqrt(252) if not first_6m.empty else np.nan

    sector_te_specific[sector] = {"TE_3M": te_3m, "TE_6M": te_6m}
daily_std = first_3m.std()
annualised_te = daily_std * np.sqrt(252)

print("Daily std (decimal):", daily_std)
print("Annualised TE (decimal):", annualised_te)
print("Annualised TE (bps):", annualised_te * 10000)

# Convert to DataFrame for easy view
te_specific_df = pd.DataFrame(sector_te_specific).T
print(te_specific_df.round(4).sort_values(by = "TE_3M", ascending=False))

Daily std (decimal): 0.001208723138438868
Annualised TE (decimal): 0.019187884969432453
Annualised TE (bps): 191.87884969432454
                         TE_3M   TE_6M
Financials              0.0549  0.0489
Information Technology  0.0301  0.0374
Consumer Discretionary  0.0275  0.0309
Industrials             0.0260  0.0270
Real Estate             0.0243  0.0271
Materials               0.0237  0.0234
Communication Services  0.0237  0.0285
Utilities               0.0229  0.0202
Health Care             0.0218  0.0313
Consumer Staples        0.0192  0.0223
Energy                  0.0184  0.0182

Now the same but with different market composition in the months after:

In [520]:
buy_and_hold_sector_returns = {}
for sector, data in optimal_portfolios_shrink.items():
    w_b = data['w_b_vec']                 # initial benchmark weights
    tickers = data['stock_labels']       # stock labels for the sector
    
    # Compute sector-level buy-and-hold benchmark returns
    sector_returns = compute_buy_and_hold_returns(
        monthly_returns_23_25,
        weights=w_b,
        stock_labels=tickers
    )
    
    buy_and_hold_sector_returns[sector] = sector_returns

buy_and_hold_df = pd.DataFrame(buy_and_hold_sector_returns)



decarb_sector_returns = {}

for sector, data in optimal_portfolios_shrink.items():
    w_opt = data['w_opt']
    tickers = data['stock_labels']
    
    sector_returns = compute_fixed_weight_returns(
        monthly_returns_23_25,
        weights=w_opt,
        stock_labels=tickers
    )
    
    decarb_sector_returns[sector] = sector_returns


sector_tracking_errors = {}

for sector in buy_and_hold_sector_returns:
    # Get returns
    r_b = buy_and_hold_sector_returns[sector]
    r_d = decarb_sector_returns[sector]
    
    # Align indices (just in case)
    common_index = r_b.index.intersection(r_d.index)
    active_returns = r_d.loc[common_index] - r_b.loc[common_index]
    
    # Monthly tracking error
    te_monthly = active_returns.std()
    
    # Annualised tracking error
    te_annualised = te_monthly * np.sqrt(12)
    
    # Store
    sector_tracking_errors[sector] = te_annualised


te_df_total = pd.DataFrame.from_dict(sector_tracking_errors, orient='index', columns=['Annualised Tracking Error'])
te_df_total = te_df_total.sort_values(by='Annualised Tracking Error', ascending=False)
print(te_df_total)

                        Annualised Tracking Error
Information Technology                   0.062288
Communication Services                   0.050658
Health Care                              0.041415
Industrials                              0.039865
Consumer Staples                         0.037306
Consumer Discretionary                   0.036182
Financials                               0.031458
Materials                                0.031355
Real Estate                              0.029201
Utilities                                0.027319
Energy                                   0.019816

In [521]:
sector_tracking_errors = {}

for sector in buy_and_hold_sector_returns:
    # Get returns
    r_b = buy_and_hold_sector_returns[sector]
    r_d = decarb_sector_returns[sector]
    
    # Align indices (just in case)
    common_index = r_b.index.intersection(r_d.index)
    r_b = r_b.loc[common_index]
    r_d = r_d.loc[common_index]
    
    active_returns = r_d - r_b

    # --- Restrict to first 3M and 6M ---
    first_3m = active_returns.loc["2023-01-01":"2023-03-31"]
    first_6m = active_returns.loc["2023-01-01":"2023-06-30"]
    
    # Compute TE (annualized from daily std)
    te_3m = first_3m.std() * np.sqrt(252) if not first_3m.empty else np.nan
    te_6m = first_6m.std() * np.sqrt(252) if not first_6m.empty else np.nan

    sector_tracking_errors[sector] = {"TE_3M": te_3m, "TE_6M": te_6m}

# Convert to DataFrame
te_df_total = pd.DataFrame(sector_tracking_errors).T
print(te_df_total.round(4).sort_values(by="TE_6M", ascending=False))

                         TE_3M   TE_6M
Industrials             0.2816  0.1540
Financials              0.0792  0.1520
Information Technology  0.1921  0.1447
Consumer Discretionary  0.0334  0.1148
Real Estate             0.0085  0.1065
Communication Services  0.0201  0.0786
Materials               0.1393  0.0753
Energy                  0.0169  0.0739
Consumer Staples        0.1320  0.0700
Health Care             0.1011  0.0691
Utilities               0.0169  0.0563

Higher tracking error -> for Information Technology, Communication Services and Health Care/Industrials

In [522]:
def expected_shortfall(x: pd.Series, alpha: float = 0.05) -> float:
    """
    ES/CVaR of a return series at level alpha.
    Returns the (negative) mean of the worst alpha tail (i.e., average loss).
    If the series is too short, returns np.nan.
    """
    x = pd.Series(x).dropna()
    if len(x) == 0:
        return np.nan
    var_alpha = np.percentile(x, 100 * alpha)
    tail = x[x <= var_alpha]
    if len(tail) == 0:
        return np.nan
    return tail.mean()  # likely negative for downside

sector_metrics = {}

for sector in buy_and_hold_sector_returns:
    r_b = buy_and_hold_sector_returns[sector]
    r_d = decarb_sector_returns[sector]

    # align
    idx = r_b.index.intersection(r_d.index)
    active = (r_d.loc[idx] - r_b.loc[idx]).dropna()

    if len(active) < 6:
        continue

    # Standard (variance-based) TE
    te_monthly = active.std()
    te_annual = te_monthly * np.sqrt(12)

    # Tail TE (ES / CVaR). Report absolute magnitude for readability.
    es_5 = expected_shortfall(active, alpha=0.05)         # negative number (downside)
    es_1 = expected_shortfall(active, alpha=0.01)         # deeper tail
    es_5_abs = abs(es_5)
    es_1_abs = abs(es_1)

    sector_metrics[sector] = {
        "TE_Annual": te_annual,          # variance-based, annualised
        "ES_5pct_monthly": es_5,         # negative value (avg worst 5% months)
        "ES_1pct_monthly": es_1,         # negative value (avg worst 1% months)
        "ES_5pct_abs": es_5_abs,         # positive magnitude
        "ES_1pct_abs": es_1_abs,
    }

te_df = pd.DataFrame.from_dict(sector_metrics, orient='index')
# Optional formatting in bps / %
print(te_df.sort_values("ES_5pct_monthly", ascending=True))

                        TE_Annual  ES_5pct_monthly  ES_1pct_monthly  \
Information Technology   0.062288        -0.042109        -0.046247
Communication Services   0.050658        -0.036509        -0.039145
Industrials              0.039865        -0.025241        -0.027643
Health Care              0.041415        -0.024569        -0.026281
Consumer Staples         0.037306        -0.022084        -0.026788
Materials                0.031355        -0.017445        -0.019360
Utilities                0.027319        -0.017366        -0.023284
Consumer Discretionary   0.036182        -0.016414        -0.018885
Real Estate              0.029201        -0.013658        -0.014514
Financials               0.031458        -0.013209        -0.013421
Energy                   0.019816        -0.012538        -0.012800

                        ES_5pct_abs  ES_1pct_abs
Information Technology     0.042109     0.046247
Communication Services     0.036509     0.039145
Industrials                0.025241     0.027643
Health Care                0.024569     0.026281
Consumer Staples           0.022084     0.026788
Materials                  0.017445     0.019360
Utilities                  0.017366     0.023284
Consumer Discretionary     0.016414     0.018885
Real Estate                0.013658     0.014514
Financials                 0.013209     0.013421
Energy                     0.012538     0.012800

Highest expected shortfall also highest for Info. Tech., Comm. Serv, and Industrials /Health Care

In [523]:

sector_metrics = {}  # New dictionary to store all metrics

rf_monthly = 0.0  # Assumed risk-free rate (adjust if needed)

for sector in buy_and_hold_sector_returns:
    # Get returns
    r_b = buy_and_hold_sector_returns[sector]
    r_d = decarb_sector_returns[sector]
    
    # Align indices
    common_index = r_b.index.intersection(r_d.index)
    r_b = r_b.loc[common_index]
    r_d = r_d.loc[common_index]
    active_returns = r_d - r_b

    # === Tracking Error ===
    te_monthly = active_returns.std()
    te_annualised = te_monthly * np.sqrt(12)

    # === Benchmark metrics ===
    ret_b = r_b.mean() * 12
    vol_b = r_b.std() * np.sqrt(12)
    sharpe_b = (ret_b - rf_monthly * 12) / vol_b if vol_b != 0 else np.nan

    # === Decarbonised metrics ===
    ret_d = r_d.mean() * 12
    vol_d = r_d.std() * np.sqrt(12)
    sharpe_d = (ret_d - rf_monthly * 12) / vol_d if vol_d != 0 else np.nan

    # Store all metrics
    sector_metrics[sector] = {
        "Annualised Tracking Error": round(te_annualised, 3),
        "Return_B": round(ret_b, 2),
        "Vol_B": round(vol_b, 2),
        "Sharpe_B": round(sharpe_b, 2),
        "Return_D": round(ret_d, 2),
        "Vol_D": round(vol_d, 2),
        "Sharpe_D": round(sharpe_d, 2)
    }

# Convert to DataFrame
metrics_df = pd.DataFrame.from_dict(sector_metrics, orient='index')
metrics_df = metrics_df.sort_values(by="Annualised Tracking Error", ascending=False)
print(metrics_df)

                        Annualised Tracking Error  Return_B  Vol_B  Sharpe_B  \
Information Technology                      0.062      0.33   0.19      1.69
Communication Services                      0.051      0.32   0.17      1.94
Health Care                                 0.041      0.03   0.13      0.25
Industrials                                 0.040      0.16   0.16      1.01
Consumer Staples                            0.037      0.10   0.11      0.85
Consumer Discretionary                      0.036      0.21   0.20      1.03
Materials                                   0.031      0.05   0.17      0.31
Financials                                  0.031      0.19   0.17      1.15
Real Estate                                 0.029      0.06   0.18      0.35
Utilities                                   0.027      0.08   0.15      0.52
Energy                                      0.020      0.03   0.19      0.15

                        Return_D  Vol_D  Sharpe_D
Information Technology      0.25   0.17      1.43
Communication Services      0.27   0.14      1.93
Health Care                -0.01   0.14     -0.05
Industrials                 0.12   0.15      0.86
Consumer Staples            0.05   0.11      0.48
Consumer Discretionary      0.21   0.19      1.11
Materials                   0.04   0.18      0.24
Financials                  0.19   0.18      1.08
Real Estate                 0.05   0.18      0.29
Utilities                   0.08   0.16      0.49
Energy                      0.00   0.20      0.00

Returns of the benchmark almost equal to the returns of the decarb portfolios, except for Inf. Technology and Communication Services even though volatility is slightly higher for the benchmark for these two sectors. The Sharpe Ratio are not too divergent but they differ more for Inf. Technology and Energy. Consumer Discretionary is the only sector with higher Sharpe Ratio for the decarbonised portfolio.

# TE testing against real benchmark

In [524]:
def load_and_process(file, duplicate_map=None):
    # --- Prices ---
    price = pd.read_excel(file, sheet_name='CLOSE PRICE', header=4).iloc[:-1]
    price.columns = price.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
    price.index = pd.to_datetime(price.Code)
    price = price.iloc[:, 1:]
    
    # --- Free-float shares ---
    ffnosh = pd.read_excel(file, sheet_name='FFNOSH', header=4).iloc[:-1]
    ffnosh.columns = ffnosh.columns.str.replace(r'\(.*?\)', '', regex=True).str.strip()
    ffnosh.index = pd.to_datetime(ffnosh.Code)
    ffnosh = ffnosh.iloc[:, 1:]
    

    # Handle duplicates (GOOG/GOOGL, FOX/FOXA, NWS/NWSA)
    if duplicate_map:
        price = price.rename(columns=duplicate_map)
        ffnosh = ffnosh.rename(columns=duplicate_map)

        # Weighted aggregation
        weighted_price = (price * ffnosh).groupby(axis=1, level=0).sum() / ffnosh.groupby(axis=1, level=0).sum()
        total_ffnosh = ffnosh.groupby(axis=1, level=0).sum()
    else:
        weighted_price = price
        total_ffnosh = ffnosh

    # Return clean DataFrames
    return weighted_price, total_ffnosh

In [528]:
# Load mappings from your SYMBOL file
type_lseg = pd.read_excel("Data/symbol_comp_1222.xlsm", sheet_name="SYMBOL", dtype=str).iloc[0].values[1:]
symbol_lseg = pd.read_excel("Data/symbol_comp_1222.xlsm", sheet_name="SYMBOL", dtype=str, header=2)
symbol_lseg = symbol_lseg.iloc[:1].transpose().reset_index().rename(columns={"index": "NAME", 0: "SYMBOL"}).iloc[1:]
symbol_lseg['TYPE'] = type_lseg
symbol_type_matches = symbol_lseg.set_index("TYPE")["SYMBOL"].to_dict()

# Duplicate mapping
duplicate_map = {"89257H": "89257J", "9406MC": "9406MA", "29026M": "871997"}

# Load first 3 months (Jan–Mar 2023)
price1, ffnosh1 = load_and_process(
    "Data/price_div_comp_1222_0323.xlsm",
    duplicate_map=duplicate_map,
)

# Load next 3 months (Apr–Jun 2023)
price2, ffnosh2 = load_and_process(
    "Data/price_div_comp_0423_0623.xlsm",
    duplicate_map=duplicate_map
)

/var/folders/n9/cy4s67js3v58hhczg4lxj5jr0000gq/T/ipykernel_69957/81507838.py:21: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  weighted_price = (price * ffnosh).groupby(axis=1, level=0).sum() / ffnosh.groupby(axis=1, level=0).sum()
/var/folders/n9/cy4s67js3v58hhczg4lxj5jr0000gq/T/ipykernel_69957/81507838.py:21: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  weighted_price = (price * ffnosh).groupby(axis=1, level=0).sum() / ffnosh.groupby(axis=1, level=0).sum()
/var/folders/n9/cy4s67js3v58hhczg4lxj5jr0000gq/T/ipykernel_69957/81507838.py:22: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  total_ffnosh = ffnosh.groupby(axis=1, level=0).sum()
/var/folders/n9/cy4s67js3v58hhczg4lxj5jr0000gq/T/ipykernel_69957/81507838.py:21: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  weighted_price = (price * ffnosh).groupby(axis=1, level=0).sum() / ffnosh.groupby(axis=1, level=0).sum()
/var/folders/n9/cy4s67js3v58hhczg4lxj5jr0000gq/T/ipykernel_69957/81507838.py:21: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  weighted_price = (price * ffnosh).groupby(axis=1, level=0).sum() / ffnosh.groupby(axis=1, level=0).sum()
/var/folders/n9/cy4s67js3v58hhczg4lxj5jr0000gq/T/ipykernel_69957/81507838.py:22: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  total_ffnosh = ffnosh.groupby(axis=1, level=0).sum()

In [529]:
price_all = pd.concat([price1, price2])
ffnosh_all = pd.concat([ffnosh1, ffnosh2])

# # Align indexes and columns just in case
# price_all, ffnosh_all = price_all.align(ffnosh_all, axis=1, join="inner")
# price_all = price_all.sort_index()
# ffnosh_all = ffnosh_all.sort_index()

In [531]:
# Columns that contain at least one NaN
cols_with_nan = ffnosh_all.columns[ffnosh_all.isna().any()].tolist()

print("Columns with NaN:", cols_with_nan)

Columns with NaN: ['28709C', '518628', '906838', '912146', '14406L', '2709JR', '50143H', '755666']

In [532]:
symbol_type_matches_2 = pd.read_excel("Data/symbol_comp_0423_0623.xlsm", sheet_name='SYMBOL', skiprows=1)

In [533]:
symbol_type_matches_2.rename(columns={'Type':'TYPE', 'WC05601':'SYMBOL'}, inplace=True)

In [534]:
symbol_type_matches_2 = symbol_type_matches_2.set_index("TYPE")["SYMBOL"].to_dict()

In [535]:
symbol_type_matches = symbol_type_matches | symbol_type_matches_2

In [536]:
symbol_type_matches = {str(k): v for k, v in symbol_type_matches.items()}

In [537]:
for symbol in cols_with_nan:
    try:
        print(symbol_type_matches[symbol], symbol)
    except:
        print(symbol)

SBNY 28709C
SIVBQ 518628
LUMN 906838
VNO 912146
BG 14406L
GEHC 2709JR
PODD 50143H
FICO 755666

In [539]:
data = pd.read_excel("Data/dataset_comp_1222_without_ceg_ogn.xlsx")
# Float-adjusted market cap
float_mcap = price_all * ffnosh_all

In [541]:
sector_map = data.set_index("SYMBOL")["GICS Sector"].to_dict()
sector_map_series = pd.Series(sector_map)

sector_map_series['BG'] = "Consumer Staples" 
sector_map_series['GEHC'] = "Health Care"
sector_map_series['PODD'] = "Health Care"
sector_map_series['FICO'] = "Information Technology"
# add the new 4 stocks

In [542]:
float_mcap = float_mcap.rename(columns=symbol_type_matches)

In [543]:
float_mcap = float_mcap.rename(columns={'BRK.A':'BRK-B'})

In [544]:
# Columns in float_mcap but not in sector_map_series index
missing_cols = set(float_mcap.columns) - set(sector_map_series.index)

print("Missing columns:", missing_cols)

Missing columns: {'CEG', 'OGN', 'PSKY'}

In [545]:
sector_map_series = sector_map_series.rename(index={"PARA": "PSKY"})

In [546]:
# Ensure float_mcap has same columns as sector map
float_mcap = float_mcap.loc[:, sector_map_series.index]

# Compute sector-level weights
sector_weights = {}
for sector in sector_map_series.unique():
    tickers = sector_map_series[sector_map_series == sector].index
    sector_mcap = float_mcap[tickers].sum(axis=1)
    sector_weights[sector] = float_mcap[tickers].div(sector_mcap, axis=0)

# Example: check Info Tech weights for Jan–Jun 2023
print(sector_weights["Information Technology"].head())
print(sector_weights["Information Technology"].tail())

                 IBM       AMD      ADBE       ADI      ANSS      AAPL  \
Code
2022-12-30  0.016959  0.011036  0.022591  0.012414  0.002806  0.282518
2023-01-02  0.016986  0.011053  0.021492  0.012434  0.002811  0.282950
2023-01-03  0.017275  0.011060  0.021781  0.012466  0.002811  0.275716
2023-01-04  0.017417  0.011179  0.022089  0.012741  0.002864  0.278783
2023-01-05  0.017594  0.011001  0.021692  0.012519  0.002788  0.281568

                AMAT      ADSK      VRSN       APH  ...       GEN       STX  \
Code                                                ...
2022-12-30  0.010989  0.005796  0.002658  0.005472  ...  0.001508  0.001473
2023-01-02  0.011020  0.005806  0.002662  0.005475  ...  0.001500  0.001476
2023-01-03  0.011081  0.005823  0.002649  0.005561  ...  0.001532  0.001473
2023-01-04  0.011386  0.005916  0.002699  0.005648  ...  0.001551  0.001491
2023-01-05  0.011460  0.005850  0.002681  0.005704  ...  0.001528  0.001552

                ANET      KEYS      QRVO      SEDG       HPE       HPQ  \
Code
2022-12-30  0.004447  0.004117  0.001247  0.002243  0.002765  0.003637
2023-01-02  0.004455  0.004122  0.001246  0.002247  0.002771  0.003646
2023-01-03  0.004493  0.004169  0.001241  0.002292  0.002823  0.003674
2023-01-04  0.004234  0.004162  0.001268  0.002335  0.002889  0.003741
2023-01-05  0.004157  0.004208  0.001284  0.002270  0.002954  0.003818

                 DXC  FICO
Code
2022-12-30  0.000895   NaN
2023-01-02  0.000896   NaN
2023-01-03  0.000947   NaN
2023-01-04  0.000965   NaN
2023-01-05  0.000967   NaN

[5 rows x 64 columns]
                 IBM       AMD      ADBE       ADI      ANSS      AAPL  \
Code
2023-06-23  0.011615  0.012672  0.022837  0.008938  0.002387  0.273416
2023-06-26  0.011915  0.012519  0.022838  0.009055  0.002388  0.274312
2023-06-27  0.011769  0.012601  0.022844  0.009164  0.002394  0.272957
2023-06-28  0.011719  0.012578  0.022528  0.009047  0.002402  0.274726
2023-06-29  0.011911  0.012686  0.022566  0.009017  0.002412  0.274918

                AMAT      ADSK      VRSN       APH  ...       GEN       STX  \
Code                                                ...
2023-06-23  0.010243  0.004231  0.001852  0.003632  ...  0.000801  0.001071
2023-06-26  0.010638  0.004252  0.001857  0.003688  ...  0.000826  0.001087
2023-06-27  0.010932  0.004294  0.001837  0.003691  ...  0.000828  0.001093
2023-06-28  0.010746  0.004283  0.001848  0.003704  ...  0.000819  0.001084
2023-06-29  0.010749  0.004276  0.001847  0.003742  ...  0.000825  0.001089

                ANET      KEYS      QRVO      SEDG       HPE       HPQ  \
Code
2023-06-23  0.003646  0.002462  0.000912  0.001363  0.002117  0.002541
2023-06-26  0.003735  0.002504  0.000936  0.001400  0.002123  0.002583
2023-06-27  0.003790  0.002511  0.000948  0.001414  0.002087  0.002538
2023-06-28  0.003784  0.002517  0.000935  0.001430  0.002078  0.002547
2023-06-29  0.003863  0.002551  0.000940  0.001406  0.002113  0.002576

                 DXC      FICO
Code
2023-06-23  0.000644  0.001839
2023-06-26  0.000657  0.001841
2023-06-27  0.000646  0.001821
2023-06-28  0.000644  0.001850
2023-06-29  0.000647  0.001869

[5 rows x 64 columns]

In [548]:
data.loc[data['SYMBOL'] == 'SBNY']

,Unnamed: 0,NAME,TYPE,SYMBOL,GICS Sector,ffnosh last day dic 22,Price last day dic 22,Scope 1,Scope 2,Scope 3,...,Sector_Information Technology,Sector_Materials,Sector_Real Estate,Sector_Utilities,Scope 1 Imputed,Scope 2 Imputed,Scope 3 Imputed,weight_in_sector,float_mcap,rank_in_sector
338,338,SIGNATURE BANK,28709C,SBNY,Financials,52890,116.12,18865000.0,6400000.0,161000000.0,...,0,0,0,0,1.0,1.0,1.0,0.001408,6141586.8,73

In [550]:
sector_weights['Financials']['SBNY']

Code
2022-12-30    0.001401
2023-01-02    0.001401
2023-01-03    0.001371
2023-01-04    0.001404
2023-01-05    0.001332
                ...
2023-06-23         NaN
2023-06-26         NaN
2023-06-27         NaN
2023-06-28         NaN
2023-06-29         NaN
Name: SBNY, Length: 739, dtype: float64

## Testing TEs across 6 months time windows (period 2023-2025), with 2% TE constraint:

In [23]:

sector_tracking_errors = {}
sector_tracking_errors_6m = {}

for sector in buy_and_hold_sector_returns:
    r_b = buy_and_hold_sector_returns[sector]
    r_d = decarb_sector_returns[sector]

    # Align indices
    common_index = r_b.index.intersection(r_d.index)
    r_b = r_b.loc[common_index]
    r_d = r_d.loc[common_index]

    df = pd.DataFrame({'r_b': r_b, 'r_d': r_d})
    df['active_return'] = df['r_d'] - df['r_b']

    six_month_windows = df.resample('6ME')
    te_annualised_list = []

    for _, window in six_month_windows:
        if len(window) >= 3:
            te_6m = window['active_return'].std()
            te_annualised = te_6m * np.sqrt(2)
            te_annualised_list.append(te_annualised)

    sector_tracking_errors_6m[sector] = te_annualised_list
    sector_tracking_errors[sector] = (
        np.mean(te_annualised_list) if te_annualised_list else np.nan
    )

# --- Build Table ---
# Get the max number of 6M periods across all sectors (to align column count)
max_periods = max(len(v) for v in sector_tracking_errors_6m.values())

# Build rows for DataFrame
rows = {}
for sector, te_list in sector_tracking_errors_6m.items():
    row = te_list + [np.nan] * (max_periods - len(te_list))  # pad with NaNs
    row.append(np.mean(te_list) if te_list else np.nan)
    rows[sector] = row

# Create column labels
columns = [f"TE_time_window_{i+1}" for i in range(max_periods)] + ["Avg_TE"]

# Create and display DataFrame
te_df = pd.DataFrame.from_dict(rows, orient='index', columns=columns)
print(te_df.round(4).sort_values(by='Avg_TE', ascending=False))

                        TE_time_window_1  TE_time_window_2  TE_time_window_3  \
Information Technology            0.0132            0.0235            0.0384
Communication Services            0.0073            0.0194            0.0240
Health Care                       0.0084            0.0194            0.0244
Industrials                       0.0149            0.0075            0.0102
Consumer Staples                  0.0059            0.0124            0.0187
Consumer Discretionary            0.0117            0.0096            0.0171
Financials                        0.0113            0.0152            0.0129
Real Estate                       0.0094            0.0092            0.0084
Materials                         0.0074            0.0159            0.0098
Utilities                         0.0051            0.0103            0.0060
Energy                            0.0060            0.0093            0.0070

                        TE_time_window_4  TE_time_window_5  Avg_TE
Information Technology            0.0214            0.0325  0.0258
Communication Services            0.0222            0.0311  0.0208
Health Care                       0.0187            0.0153  0.0172
Industrials                       0.0217            0.0237  0.0156
Consumer Staples                  0.0140            0.0260  0.0154
Consumer Discretionary            0.0241            0.0125  0.0150
Financials                        0.0094            0.0177  0.0133
Real Estate                       0.0155            0.0187  0.0123
Materials                         0.0133            0.0098  0.0113
Utilities                         0.0124            0.0158  0.0099
Energy                            0.0102            0.0117  0.0088

The TE averaged across 6 months time windows is significantly lower (in the range less than 1% to 2.5%) than the TE calculated over the entire period (between 2%-6%). The difference is especially high for the three sectors with the highest TE.

In [24]:
sector_geo_annual_cum_active = {}
sector_cum_active_6m = {}

for sector in buy_and_hold_sector_returns:
    r_b = buy_and_hold_sector_returns[sector]
    r_d = decarb_sector_returns[sector]

    # Align indices
    common_index = r_b.index.intersection(r_d.index)
    r_b = r_b.loc[common_index]
    r_d = r_d.loc[common_index]

    df = pd.DataFrame({'r_b': r_b, 'r_d': r_d})
    df['active_return'] = df['r_d'] - df['r_b']

    six_month_windows = df.resample('6ME')
    car_list = []

    for _, window in six_month_windows:
        if len(window) >= 3:
            # Cumulative active return per 6M window
            car_6m = (1.0 + window['active_return']).prod() - 1.0
            car_list.append(car_6m)

    sector_cum_active_6m[sector] = car_list

    if car_list:
        # geometric mean of 6M CARs, annualised
        geo_6m = np.prod([1 + x for x in car_list])**(1/len(car_list)) - 1
        geo_annual = (1 + geo_6m)**2 - 1   # annualise (since window = 6M)
        sector_geo_annual_cum_active[sector] = float(geo_annual)
    else:
        sector_geo_annual_cum_active[sector] = np.nan

# --- Build Table ---
rows = {sector: car_list + [sector_geo_annual_cum_active[sector]]
        for sector, car_list in sector_cum_active_6m.items()}

max_periods_car = max(len(v) for v in sector_cum_active_6m.values()) if sector_cum_active_6m else 0
columns = [f"CAR_6M_window_{i+1}" for i in range(max_periods_car)] + ["GeoMean_CAR_Annual"]

car_df = pd.DataFrame.from_dict(rows, orient='index', columns=columns)
print(car_df.round(4).sort_values(by="GeoMean_CAR_Annual", ascending=False))

                        CAR_6M_window_1  CAR_6M_window_2  CAR_6M_window_3  \
Consumer Discretionary           0.0013          -0.0042           0.0143
Utilities                        0.0145           0.0019           0.0195
Financials                      -0.0315           0.0190          -0.0072
Materials                       -0.0207          -0.0143           0.0168
Real Estate                     -0.0232          -0.0159           0.0213
Energy                          -0.0098          -0.0112          -0.0084
Industrials                      0.0223           0.0052          -0.0471
Health Care                     -0.0350          -0.0047          -0.0215
Consumer Staples                -0.0280          -0.0129          -0.0491
Communication Services          -0.0079          -0.0691           0.0153
Information Technology          -0.0360          -0.0455          -0.0393

                        CAR_6M_window_4  CAR_6M_window_5  GeoMean_CAR_Annual
Consumer Discretionary          -0.0101          -0.0014             -0.0001
Utilities                       -0.0499           0.0097             -0.0024
Financials                      -0.0055           0.0119             -0.0056
Materials                       -0.0337           0.0352             -0.0073
Real Estate                     -0.0149           0.0095             -0.0096
Energy                          -0.0225          -0.0106             -0.0249
Industrials                     -0.0467          -0.0155             -0.0333
Health Care                     -0.0335           0.0023             -0.0369
Consumer Staples                -0.0310           0.0120             -0.0436
Communication Services          -0.0476          -0.0191             -0.0516
Information Technology          -0.0030          -0.0731             -0.0777

In [24]:

# Containers
sector_tracking_errors_6m = {}
sharpe_ratios_b_6m = {}
sharpe_ratios_d_6m = {}
returns_b_6m = {}
returns_d_6m = {}
vol_b_6m = {}
vol_d_6m = {}

summary_metrics = {}

for sector in buy_and_hold_sector_returns:
    r_b = buy_and_hold_sector_returns[sector]
    r_d = decarb_sector_returns[sector]

    # Align indices
    common_index = r_b.index.intersection(r_d.index)
    r_b = r_b.loc[common_index]
    r_d = r_d.loc[common_index]

    df = pd.DataFrame({'r_b': r_b, 'r_d': r_d})
    df['active_return'] = df['r_d'] - df['r_b']

    six_month_windows = df.resample('6ME')

    te_annualised_list = []
    sharpe_b_list = []
    sharpe_d_list = []
    return_b_list = []
    return_d_list = []
    vol_b_list = []
    vol_d_list = []

    for _, window in six_month_windows:
        if len(window) >= 3:
            # --- Tracking Error ---
            te_6m = window['active_return'].std()
            te_annualised = te_6m * np.sqrt(2)
            te_annualised_list.append(te_annualised)

            # --- Benchmark Metrics ---
            r_b_win = window['r_b']
            mean_b = r_b_win.mean() * 12
            std_b = r_b_win.std() * np.sqrt(12)
            sharpe_b = mean_b / std_b if std_b != 0 else np.nan
            return_b_list.append(mean_b)
            vol_b_list.append(std_b)
            sharpe_b_list.append(sharpe_b)

            # --- Decarb Metrics ---
            r_d_win = window['r_d']
            mean_d = r_d_win.mean() * 12
            std_d = r_d_win.std() * np.sqrt(12)
            sharpe_d = mean_d / std_d if std_d != 0 else np.nan
            return_d_list.append(mean_d)
            vol_d_list.append(std_d)
            sharpe_d_list.append(sharpe_d)

    # Store lists per sector
    sector_tracking_errors_6m[sector] = te_annualised_list
    returns_b_6m[sector] = return_b_list
    returns_d_6m[sector] = return_d_list
    vol_b_6m[sector] = vol_b_list
    vol_d_6m[sector] = vol_d_list
    sharpe_ratios_b_6m[sector] = sharpe_b_list
    sharpe_ratios_d_6m[sector] = sharpe_d_list

    # Store averaged metrics in summary table
    summary_metrics[sector] = {
        "Avg_TE": np.nanmean(te_annualised_list),
        "Avg_Return_B": np.nanmean(return_b_list),
        "Avg_Return_D": np.nanmean(return_d_list),
        "Avg_Vol_B": np.nanmean(vol_b_list),
        "Avg_Vol_D": np.nanmean(vol_d_list),
        "Avg_Sharpe_B": np.nanmean(sharpe_b_list),
        "Avg_Sharpe_D": np.nanmean(sharpe_d_list)
    }

# Get max number of 6M periods
max_periods = max(len(v) for v in sector_tracking_errors_6m.values())

# Build detailed rows
detailed_rows = {}

for sector in sector_tracking_errors_6m:
    row = {}

    # TE per 6M
    te_list = sector_tracking_errors_6m[sector]
    for i, val in enumerate(te_list):
        row[f"TE_{i+1}"] = val
    row["Avg_TE"] = np.nanmean(te_list)

    # Returns Benchmark
    ret_b_list = returns_b_6m[sector]
    for i, val in enumerate(ret_b_list):
        row[f"Return_B_{i+1}"] = val
    row["Avg_Return_B"] = np.nanmean(ret_b_list)

    # Returns Decarb
    ret_d_list = returns_d_6m[sector]
    for i, val in enumerate(ret_d_list):
        row[f"Return_D_{i+1}"] = val
    row["Avg_Return_D"] = np.nanmean(ret_d_list)

    # Volatility Benchmark
    vol_b_list = vol_b_6m[sector]
    for i, val in enumerate(vol_b_list):
        row[f"Vol_B_{i+1}"] = val
    row["Avg_Vol_B"] = np.nanmean(vol_b_list)

    # Volatility Decarb
    vol_d_list = vol_d_6m[sector]
    for i, val in enumerate(vol_d_list):
        row[f"Vol_D_{i+1}"] = val
    row["Avg_Vol_D"] = np.nanmean(vol_d_list)

    # Sharpe Benchmark
    sharpe_b_list = sharpe_ratios_b_6m[sector]
    for i, val in enumerate(sharpe_b_list):
        row[f"Sharpe_B_{i+1}"] = val
    row["Avg_Sharpe_B"] = np.nanmean(sharpe_b_list)

    # Sharpe Decarb
    sharpe_d_list = sharpe_ratios_d_6m[sector]
    for i, val in enumerate(sharpe_d_list):
        row[f"Sharpe_D_{i+1}"] = val
    row["Avg_Sharpe_D"] = np.nanmean(sharpe_d_list)

    detailed_rows[sector] = row
# Create full table
detailed_df = pd.DataFrame.from_dict(detailed_rows, orient='index')

# Round columns selectively
rounded_df = detailed_df.copy()
for col in rounded_df.columns:
    if col.startswith("TE_") or col == "Avg_TE":
        rounded_df[col] = rounded_df[col].round(3)
    else:
        rounded_df[col] = rounded_df[col].round(2)

# Optional: sort by average Sharpe_D
rounded_df = rounded_df.sort_values(by="Avg_Sharpe_D", ascending=False)

# Display the full table
pd.set_option('display.max_columns', None)
print(rounded_df)

                         TE_1   TE_2   TE_3   TE_4   TE_5  Avg_TE  Return_B_1  \
Communication Services  0.007  0.019  0.024  0.022  0.031   0.021        0.60
Information Technology  0.013  0.024  0.038  0.021  0.032   0.026        0.59
Consumer Discretionary  0.012  0.010  0.017  0.024  0.013   0.015        0.38
Financials              0.011  0.015  0.013  0.009  0.018   0.013       -0.01
Industrials             0.015  0.007  0.010  0.022  0.024   0.016        0.16
Utilities               0.005  0.010  0.006  0.012  0.016   0.010       -0.04
Consumer Staples        0.006  0.012  0.019  0.014  0.026   0.015        0.07
Materials               0.007  0.016  0.010  0.013  0.010   0.011        0.07
Energy                  0.006  0.009  0.007  0.010  0.012   0.009        0.17
Health Care             0.008  0.019  0.024  0.019  0.015   0.017        0.12
Real Estate             0.009  0.009  0.008  0.016  0.019   0.012       -0.01

                        Return_B_2  Return_B_3  Return_B_4  Return_B_5  \
Communication Services        0.35        0.22        0.31        0.26
Information Technology        0.38        0.31        0.04        0.36
Consumer Discretionary        0.24        0.05        0.32        0.07
Financials                    0.36        0.27        0.32        0.06
Industrials                   0.24        0.19        0.09        0.20
Utilities                    -0.03        0.48        0.07        0.04
Consumer Staples              0.11        0.25        0.11       -0.04
Materials                     0.16        0.17       -0.08        0.01
Energy                       -0.03        0.17        0.03       -0.10
Health Care                   0.20        0.19       -0.08       -0.26
Real Estate                   0.18        0.27        0.04       -0.07

                        Avg_Return_B  Return_D_1  Return_D_2  Return_D_3  \
Communication Services          0.35        0.59        0.21        0.25
Information Technology          0.34        0.52        0.29        0.23
Consumer Discretionary          0.21        0.39        0.23        0.08
Financials                      0.20       -0.07        0.40        0.26
Industrials                     0.18        0.21        0.25        0.10
Utilities                       0.10       -0.02       -0.03        0.52
Consumer Staples                0.10        0.01        0.08        0.15
Materials                       0.06        0.03        0.13        0.20
Energy                          0.05        0.16       -0.05        0.15
Health Care                     0.03        0.05        0.19        0.15
Real Estate                     0.08       -0.06        0.15        0.31

                        Return_D_4  Return_D_5  Avg_Return_D  Vol_B_1  \
Communication Services        0.21        0.21          0.29     0.14
Information Technology        0.04        0.14          0.24     0.18
Consumer Discretionary        0.30        0.07          0.21     0.17
Financials                    0.31        0.09          0.20     0.20
Industrials                  -0.01        0.15          0.14     0.18
Utilities                    -0.03        0.07          0.10     0.17
Consumer Staples              0.05       -0.00          0.06     0.15
Materials                    -0.15        0.11          0.06     0.21
Energy                       -0.02       -0.14          0.02     0.22
Health Care                  -0.15       -0.26         -0.00     0.11
Real Estate                   0.01       -0.04          0.07     0.13

                        Vol_B_2  Vol_B_3  Vol_B_4  Vol_B_5  Avg_Vol_B  \
Communication Services     0.15     0.14     0.17     0.27       0.17
Information Technology     0.22     0.21     0.09     0.31       0.20
Consumer Discretionary     0.26     0.11     0.26     0.26       0.21
Financials                 0.18     0.14     0.19     0.16       0.17
Industrials                0.21     0.12     0.19     0.18       0.18
Utilities                  0.14     0.18     0.16     0.05       0.14
Consumer Staples           0.11     0.08     0.14     0.07       0.11
Materials                  0.20     0.15     0.20     0.10       0.17
Energy                     0.12     0.16     0.19     0.29       0.20
Health Care                0.13     0.12     0.16     0.11       0.13
Real Estate                0.27     0.20     0.18     0.05       0.16

                        Vol_D_1  Vol_D_2  Vol_D_3  Vol_D_4  Vol_D_5  \
Communication Services     0.13     0.13     0.11     0.13     0.19
Information Technology     0.16     0.23     0.17     0.09     0.24
Consumer Discretionary     0.14     0.24     0.13     0.23     0.23
Financials                 0.21     0.18     0.15     0.18     0.20
Industrials                0.18     0.20     0.12     0.14     0.13
Utilities                  0.16     0.15     0.18     0.17     0.09
Consumer Staples           0.15     0.13     0.08     0.12     0.02
Materials                  0.21     0.23     0.17     0.19     0.10
Energy                     0.23     0.13     0.17     0.20     0.32
Health Care                0.12     0.13     0.14     0.17     0.15
Real Estate                0.13     0.27     0.19     0.20     0.03

                        Avg_Vol_D  Sharpe_B_1  Sharpe_B_2  Sharpe_B_3  \
Communication Services       0.14        4.44        2.36        1.55
Information Technology       0.18        3.29        1.70        1.47
Consumer Discretionary       0.19        2.31        0.94        0.47
Financials                   0.18       -0.04        1.99        2.02
Industrials                  0.15        0.88        1.14        1.63
Utilities                    0.15       -0.26       -0.23        2.74
Consumer Staples             0.10        0.46        1.01        3.05
Materials                    0.18        0.34        0.81        1.09
Energy                       0.21        0.80       -0.26        1.03
Health Care                  0.14        1.16        1.52        1.58
Real Estate                  0.17       -0.07        0.68        1.37

                        Sharpe_B_4  Sharpe_B_5  Avg_Sharpe_B  Sharpe_D_1  \
Communication Services        1.78        0.98          2.22        4.51
Information Technology        0.45        1.16          1.61        3.27
Consumer Discretionary        1.22        0.27          1.04        2.67
Financials                    1.67        0.36          1.20       -0.34
Industrials                   0.47        1.10          1.05        1.18
Utilities                     0.43        0.78          0.69       -0.09
Consumer Staples              0.77       -0.53          0.95        0.08
Materials                    -0.42        0.07          0.38        0.14
Energy                        0.16       -0.36          0.27        0.67
Health Care                  -0.52       -2.30          0.29        0.45
Real Estate                   0.20       -1.42          0.15       -0.41

                        Sharpe_D_2  Sharpe_D_3  Sharpe_D_4  Sharpe_D_5  \
Communication Services        1.56        2.32        1.56        1.07
Information Technology        1.25        1.37        0.41        0.57
Consumer Discretionary        0.97        0.63        1.29        0.28
Financials                    2.27        1.73        1.68        0.46
Industrials                   1.27        0.81       -0.05        1.18
Utilities                    -0.18        2.93       -0.20        0.81
Consumer Staples              0.62        1.99        0.38       -0.08
Materials                     0.59        1.16       -0.79        1.16
Energy                       -0.39        0.88       -0.08       -0.43
Health Care                   1.49        1.05       -0.88       -1.72
Real Estate                   0.54        1.63        0.03       -1.40

                        Avg_Sharpe_D
Communication Services          2.21
Information Technology          1.38
Consumer Discretionary          1.17
Financials                      1.16
Industrials                     0.88
Utilities                       0.65
Consumer Staples                0.60
Materials                       0.45
Energy                          0.13
Health Care                     0.08
Real Estate                     0.08

In [25]:
summary_df = pd.DataFrame.from_dict(summary_metrics, orient='index')

# Optional: round and sort
summary_df = summary_df.round({
    "Avg_TE": 3,
    "Avg_Return_B": 2,
    "Avg_Return_D": 2,
    "Avg_Vol_B": 2,
    "Avg_Vol_D": 2,
    "Avg_Sharpe_B": 2,
    "Avg_Sharpe_D": 2
})

summary_df = summary_df.sort_values(by="Avg_Sharpe_D", ascending=False)

# Display full columns
pd.set_option('display.max_columns', None)
print(summary_df)

                        Avg_TE  Avg_Return_B  Avg_Return_D  Avg_Vol_B  \
Communication Services   0.021          0.35          0.29       0.17
Information Technology   0.026          0.34          0.24       0.20
Consumer Discretionary   0.015          0.21          0.21       0.21
Financials               0.013          0.20          0.20       0.17
Industrials              0.016          0.18          0.14       0.18
Utilities                0.010          0.10          0.10       0.14
Consumer Staples         0.015          0.10          0.06       0.11
Materials                0.011          0.06          0.06       0.17
Energy                   0.009          0.05          0.02       0.20
Health Care              0.017          0.03         -0.00       0.13
Real Estate              0.012          0.08          0.07       0.16

                        Avg_Vol_D  Avg_Sharpe_B  Avg_Sharpe_D
Communication Services       0.14          2.22          2.21
Information Technology       0.18          1.61          1.38
Consumer Discretionary       0.19          1.04          1.17
Financials                   0.18          1.20          1.16
Industrials                  0.15          1.05          0.88
Utilities                    0.15          0.69          0.65
Consumer Staples             0.10          0.95          0.60
Materials                    0.18          0.38          0.45
Energy                       0.21          0.27          0.13
Health Care                  0.14          0.29          0.08
Real Estate                  0.17          0.15          0.08

The Sharpe Ratio is always higher for the benchmark, especially for Consumer Staple and Health Care. The only exception where the Sharpe Ratio is higher for the decarbonised portfolio is Consumer Discretionary and Materials.

## Realized TE across different TE objectives

In [26]:
with open("Data/optimal_portfolios_by_te.pkl", "rb") as f:
    optimal_portfolios_by_te = pickle.load(f)

In [27]:
exclude_list = ['DAY', 'MRNA', 'DOW', 'FOXA', 'CARR', 'OTIS', 'CTVA']

# List of result rows
results = []

for te_cap, sector_data in optimal_portfolios_by_te.items():
    for sector, data in sector_data.items():
        stock_labels = data['stock_labels']
        w_b = data['w_b_vec']
        w_opt = data['w_opt']
        
 
        # Compute returns
        r_b = compute_buy_and_hold_returns(
            monthly_returns_23_25,
            weights=w_b,
            stock_labels=stock_labels
        )

        r_d = compute_fixed_weight_returns(
            monthly_returns_23_25,
            weights=w_opt,
            stock_labels=stock_labels
        )

        # Align indices
        common_index = r_b.index.intersection(r_d.index)
        r_b = r_b.loc[common_index]
        r_d = r_d.loc[common_index]
        active_returns = r_d - r_b

        # TE calculation
        te_monthly = active_returns.std()
        te_annualised = te_monthly * np.sqrt(12)

        # Benchmark stats
        ret_b = r_b.mean() * 12
        vol_b = r_b.std() * np.sqrt(12)
        sharpe_b = ret_b / vol_b if vol_b != 0 else np.nan

        # Optimised stats
        ret_d = r_d.mean() * 12
        vol_d = r_d.std() * np.sqrt(12)
        sharpe_d = ret_d / vol_d if vol_d != 0 else np.nan

        # Store as row
        results.append({
            "Sector": sector,
            "TE_Cap": te_cap,
            "TE_Annualised": te_annualised,
            "Return_B": ret_b,
            "Return_D": ret_d,
            "Vol_B": vol_b,
            "Vol_D": vol_d,
            "Sharpe_B": sharpe_b,
            "Sharpe_D": sharpe_d
        })


df = pd.DataFrame(results)
# Round columns as requested
df["TE_Annualised"] = df["TE_Annualised"].round(3)
df[["Return_B", "Return_D", "Sharpe_B", "Sharpe_D"]] = df[["Return_B", "Return_D", "Sharpe_B", "Sharpe_D"]].round(2)

for te in df['TE_Cap'].unique():
    df_filtered = df.loc[df['TE_Cap'] == te]
    # Sort and display
    df_filtered = df_filtered.sort_values(by=["TE_Annualised"], ascending=[False])
    print(df_filtered.loc[:, ['Sector', 'TE_Cap', 'TE_Annualised', 'Sharpe_B', 'Sharpe_D']])
    print()

                    Sector  TE_Cap  TE_Annualised  Sharpe_B  Sharpe_D
9   Communication Services    0.01          0.046      1.94      1.98
3   Information Technology    0.01          0.045      1.69      1.53
0   Consumer Discretionary    0.01          0.037      1.03      1.06
1              Health Care    0.01          0.032      0.25      0.03
6              Industrials    0.01          0.030      1.01      0.83
10        Consumer Staples    0.01          0.029      0.85      0.56
4              Real Estate    0.01          0.023      0.35      0.28
5                Materials    0.01          0.023      0.31      0.25
7               Financials    0.01          0.017      1.15      1.14
2                Utilities    0.01          0.016      0.52      0.48
8                   Energy    0.01          0.014      0.15      0.03

                    Sector  TE_Cap  TE_Annualised  Sharpe_B  Sharpe_D
14  Information Technology    0.02          0.062      1.69      1.43
20  Communication Services    0.02          0.051      1.94      1.93
12             Health Care    0.02          0.041      0.25     -0.05
17             Industrials    0.02          0.040      1.01      0.86
21        Consumer Staples    0.02          0.037      0.85      0.48
11  Consumer Discretionary    0.02          0.036      1.03      1.11
16               Materials    0.02          0.031      0.31      0.24
18              Financials    0.02          0.031      1.15      1.08
15             Real Estate    0.02          0.029      0.35      0.29
13               Utilities    0.02          0.027      0.52      0.49
19                  Energy    0.02          0.020      0.15      0.00

                    Sector  TE_Cap  TE_Annualised  Sharpe_B  Sharpe_D
25  Information Technology    0.03          0.079      1.69      1.22
31  Communication Services    0.03          0.057      1.94      1.88
23             Health Care    0.03          0.053      0.25     -0.05
28             Industrials    0.03          0.049      1.01      0.95
32        Consumer Staples    0.03          0.047      0.85      0.37
22  Consumer Discretionary    0.03          0.045      1.03      1.24
29              Financials    0.03          0.045      1.15      1.16
27               Materials    0.03          0.040      0.31      0.17
26             Real Estate    0.03          0.038      0.35      0.25
24               Utilities    0.03          0.037      0.52      0.52
30                  Energy    0.03          0.027      0.15     -0.02

                    Sector  TE_Cap  TE_Annualised  Sharpe_B  Sharpe_D
36  Information Technology    0.04          0.096      1.69      1.01
34             Health Care    0.04          0.069      0.25     -0.11
43        Consumer Staples    0.04          0.065      0.85      0.13
42  Communication Services    0.04          0.064      1.94      1.84
39             Industrials    0.04          0.063      1.01      0.89
33  Consumer Discretionary    0.04          0.055      1.03      1.27
37             Real Estate    0.04          0.052      0.35      0.22
40              Financials    0.04          0.051      1.15      1.28
38               Materials    0.04          0.050      0.31      0.09
35               Utilities    0.04          0.045      0.52      0.59
41                  Energy    0.04          0.033      0.15     -0.09

                    Sector  TE_Cap  TE_Annualised  Sharpe_B  Sharpe_D
47  Information Technology    0.05          0.112      1.69      0.77
54        Consumer Staples    0.05          0.082      0.85     -0.07
45             Health Care    0.05          0.081      0.25     -0.08
50             Industrials    0.05          0.075      1.01      0.88
53  Communication Services    0.05          0.072      1.94      1.86
44  Consumer Discretionary    0.05          0.065      1.03      1.27
48             Real Estate    0.05          0.059      0.35      0.27
46               Utilities    0.05          0.056      0.52      0.65
49               Materials    0.05          0.056      0.31      0.05
51              Financials    0.05          0.052      1.15      1.33
52                  Energy    0.05          0.038      0.15     -0.12