# Sector Summaries for All Periods

This notebook generates:
1. **Sector Imputation Summary**: Shows the percentage of stocks with imputed scope emissions by sector
2. **Sector Emissions Summary**: Shows emission statistics by sector

Both summaries are created for each period and then aggregated across all periods.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

## Configuration

In [2]:
# Define periods to analyze
PERIODS = ["0321", "0621", "0921", "1221", "0322", "0622", "0922", "1222", "0323", "0623", "0923", "1223"]

# Data directory
DATA_DIR = Path("data")
DATASETS_DIR = DATA_DIR / "datasets"

# Display options
pd.options.display.float_format = '{:,.2f}'.format
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## Helper Functions

In [3]:
def create_sector_imputation_summary(df, period):
    """
    Create sector imputation summary for a single period.
    Shows the percentage of stocks with imputed scope emissions by sector.
    
    Note: Excludes manual imputation columns (only uses automatic imputation flags)
    """
    auto_impute_flags = ['Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed']
    filled_count_cols = ['Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count']
    
    summary_rows = []
    
    for sector, group in df.groupby('GICS Sector'):
        n_stocks = len(group)
        row = {
            'Period': period,
            'Sector': sector,
            'Number of Stocks': n_stocks
        }
        
        # Automatically imputed (Scope 1/2/3)
        for col in auto_impute_flags:
            count = group[col].fillna(0).sum()  # Treat NaN as 0 (not imputed)
            scope = col.split()[1]  # e.g. "1" from "Scope 1 Imputed"
            row[f'Imputed Scope {scope} Count'] = int(count)
            row[f'Imputed Scope {scope} %'] = count / n_stocks * 100
        
        # Add filled counts - now summing binary indicators (0 or 1) per sector
        for col in filled_count_cols:
            if col in group.columns:
                # Sum the binary indicators to get count of filled companies in this sector
                filled_count = group[col].fillna(0).sum()
                scope = col.split()[2]  # e.g. "1" from "Filled Scope 1 Count"
                row[f'Filled Scope {scope} Count'] = int(filled_count)
                row[f'Filled Scope {scope} %'] = (filled_count / n_stocks * 100) if n_stocks > 0 else 0
        
        summary_rows.append(row)
    
    summary_df = pd.DataFrame(summary_rows)
    summary_df = summary_df.sort_values("Sector").reset_index(drop=True)
    
    # Round all percentage columns to integers
    percentage_cols = [col for col in summary_df.columns if '%' in col]
    summary_df[percentage_cols] = summary_df[percentage_cols].round(0).astype('Int64')
    
    # Create 'Missing Scope' = max imputed across scopes
    summary_df["Missing Scope Count"] = summary_df[
        ["Imputed Scope 1 Count", "Imputed Scope 2 Count", "Imputed Scope 3 Count"]
    ].max(axis=1)
    
    summary_df["Missing Scope (%)"] = (
        summary_df["Missing Scope Count"] / summary_df["Number of Stocks"] * 100
    ).round(0).astype('Int64')
    
    # Define column order - include filled counts and percentages
    columns_order = ['Period', 'Sector', 'Number of Stocks', 'Missing Scope Count', 'Missing Scope (%)'] + \
                    ['Filled Scope 1 Count', 'Filled Scope 1 %', 
                     'Filled Scope 2 Count', 'Filled Scope 2 %',
                     'Filled Scope 3 Count', 'Filled Scope 3 %'] + \
                    [col for col in summary_df.columns if col not in 
                     ['Period', 'Sector', 'Number of Stocks', 'Missing Scope Count', 'Missing Scope (%)',
                      'Filled Scope 1 Count', 'Filled Scope 1 %',
                      'Filled Scope 2 Count', 'Filled Scope 2 %',
                      'Filled Scope 3 Count', 'Filled Scope 3 %']]
    
    # Only include columns that exist
    columns_order = [col for col in columns_order if col in summary_df.columns]
    
    summary_df = summary_df[columns_order].sort_values("Missing Scope (%)", ascending=False).reset_index(drop=True)
    
    return summary_df

In [4]:
def sector_aggregates(df, period, top_weight_pct=0.2):
    """
    Create sector emissions summary for a single period.
    Shows emission statistics by sector.
    """
    results = []
    
    total_mcap = df["float_mcap"].sum()  # total benchmark market cap
    
    for sector, g in df.groupby("GICS Sector"):
        # Calculate Scope 1+2+3 if not present
        if 'Scope 1+2+3' not in g.columns:
            g['Scope 1+2+3'] = g['Scope 1'] + g['Scope 2'] + g['Scope 3']
        
        # absolute totals
        s1 = g["Scope 1"].sum()
        s2 = g["Scope 2"].sum()
        s3 = g["Scope 3"].sum()
        total_emissions = g["Scope 1+2+3"].sum()
        
        # percentages of each scope
        pct_s1 = s1/total_emissions if total_emissions > 0 else 0
        pct_s2 = s2/total_emissions if total_emissions > 0 else 0
        pct_s3 = s3/total_emissions if total_emissions > 0 else 0
        
        # top 5 emitters in sector
        top5 = g.nlargest(5, "Scope 1+2+3")["Scope 1+2+3"].sum() / total_emissions if total_emissions > 0 else 0
        
        # emissions captured within top X% of sector weights
        g_sorted = g.sort_values("weight_in_sector", ascending=False).copy()
        g_sorted["cum_weight"] = g_sorted["weight_in_sector"].cumsum()
        emissions_top_weight = g_sorted.loc[g_sorted["cum_weight"] <= top_weight_pct, "Scope 1+2+3"].sum()
        pct_emissions_top_weight = emissions_top_weight / total_emissions if total_emissions > 0 else 0
        
        # sector market cap as percentage of benchmark
        sector_mcap = g["float_mcap"].sum()
        sector_mcap_pct = sector_mcap / total_mcap if total_mcap > 0 else 0
        
        results.append({
            "Period": period,
            "Sector": sector,
            "Scope 1 sum": s1,
            "Scope 2 sum": s2,
            "Scope 3 sum": s3,
            "Scope 1+2+3 absolute": total_emissions,
            "% Scope 1": pct_s1,
            "% Scope 2": pct_s2,
            "% Scope 3": pct_s3,
            "% Top 5 emitters": top5,
            f"% Emissions in Top {int(top_weight_pct*100)}% Weight": pct_emissions_top_weight,
            "Avg Scope 1+2+3": g["Scope 1+2+3"].mean(),
            "Avg Scope 1": g["Scope 1"].mean(),
            "Avg Scope 2": g["Scope 2"].mean(),
            "Avg Scope 3": g["Scope 3"].mean(),
            "Var Scope 1": g["Scope 1"].std(),
            "Var Scope 2": g["Scope 2"].std(),
            "Var Scope 3": g["Scope 3"].std(),
            "Avg Carbon Intensity": g["Carbon Intensity"].mean(),
            "Aggregate Carbon Intensity": total_emissions / g["Revenue"].sum() if g["Revenue"].sum() > 0 else 0,
            "Sector Market Cap %": sector_mcap_pct
        })
    
    return pd.DataFrame(results)

In [5]:
def human_format(num):
    """Format large numbers with K, M, B, T suffixes"""
    for unit in ['', 'K', 'M', 'B', 'T']:
        if abs(num) < 1000:
            return f"{num:.1f}{unit}"
        num /= 1000
    return f"{num:.1f}P"

## Load Data for All Periods

In [6]:
# Load benchmark data for all periods
all_periods_data = {}

for period in PERIODS:
    file_path = DATASETS_DIR / f"benchmark_weights_carbon_intensity_{period}.xlsx"
    
    if file_path.exists():
        df = pd.read_excel(file_path)
        print(df.columns)
        # Calculate Scope 1+2+3 if not present
        if 'Scope 1+2+3' not in df.columns:
            df['Scope 1+2+3'] = df['Scope 1'] + df['Scope 2'] + df['Scope 3']
        
        # Calculate float_mcap from weight_in_sector if not present
        if 'float_mcap' not in df.columns:
            # Approximate float_mcap from weights (will be normalized by sector later)
            df['float_mcap'] = df['weight_in_sector']
        
        all_periods_data[period] = df
        print(f"Loaded {period}: {len(df)} companies, {df['GICS Sector'].nunique()} sectors")
    else:
        print(f"Warning: File not found for period {period}")

print(f"\nSuccessfully loaded data for {len(all_periods_data)} periods")

Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 0321: 497 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 0621: 497 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 0921: 497 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 1221: 497 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 0322: 498 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 0622: 498 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 0922: 498 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 1222: 498 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 0323: 497 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 0623: 498 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 0923: 497 companies, 11 sectors
Index(['SYMBOL', 'NAME', 'GICS Sector', 'Scope 1', 'Scope 2', 'Scope 3',
       'Revenue', 'Scope 1 Imputed', 'Scope 2 Imputed', 'Scope 3 Imputed',
       'Filled Scope 1 Count', 'Filled Scope 2 Count', 'Filled Scope 3 Count',
       'Carbon Intensity', 'weight_in_sector', 'TYPE'],
      dtype='object')
Loaded 1223: 496 companies, 11 sectors

Successfully loaded data for 12 periods

## 1. Sector Imputation Summary

### Individual Period Summaries

In [7]:
# Create imputation summary for each period
imputation_summaries = []

for period, df in all_periods_data.items():
    summary = create_sector_imputation_summary(df, period)
    imputation_summaries.append(summary)
    
    print(f"\n{'='*80}")
    print(f"Imputation Summary - Period {period}")
    print(f"{'='*80}")
    display(summary)

================================================================================
Imputation Summary - Period 0321
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,0321,Energy,23,11,48,0,0,0,0,2,9,0,0,0,0,11,48
1,0321,Industrials,74,22,30,3,4,3,4,5,7,4,5,4,5,22,30
2,0321,Health Care,63,17,27,4,6,4,6,12,19,4,6,4,6,17,27
3,0321,Financials,74,15,20,4,5,4,5,5,7,4,5,4,5,15,20
4,0321,Consumer Discretionary,58,11,19,1,2,2,3,9,16,2,3,3,5,11,19
5,0321,Information Technology,63,11,17,3,5,3,5,5,8,5,8,5,8,11,17
6,0321,Real Estate,29,5,17,1,3,1,3,4,14,1,3,1,3,5,17
7,0321,Communication Services,22,3,14,2,9,2,9,5,23,3,14,3,14,3,14
8,0321,Consumer Staples,36,4,11,1,3,1,3,0,0,0,0,0,0,4,11
9,0321,Materials,27,2,7,0,0,0,0,5,19,0,0,0,0,2,7
10,0321,Utilities,28,1,4,0,0,0,0,0,0,0,0,1,4,1,4

================================================================================
Imputation Summary - Period 0621
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,0621,Energy,22,10,45,0,0,0,0,2,9,0,0,0,0,10,45
1,0621,Industrials,74,22,30,3,4,3,4,5,7,4,5,4,5,22,30
2,0621,Health Care,63,17,27,4,6,4,6,12,19,4,6,4,6,17,27
3,0621,Financials,74,15,20,4,5,4,5,5,7,4,5,4,5,15,20
4,0621,Consumer Discretionary,58,11,19,1,2,2,3,8,14,2,3,3,5,11,19
5,0621,Information Technology,63,11,17,3,5,3,5,4,6,5,8,5,8,11,17
6,0621,Real Estate,29,5,17,1,3,1,3,4,14,1,3,1,3,5,17
7,0621,Communication Services,22,3,14,1,5,1,5,5,23,3,14,3,14,3,14
8,0621,Consumer Staples,36,4,11,1,3,1,3,1,3,0,0,0,0,4,11
9,0621,Materials,28,2,7,0,0,0,0,5,18,0,0,0,0,2,7
10,0621,Utilities,28,1,4,0,0,0,0,0,0,0,0,1,4,1,4

================================================================================
Imputation Summary - Period 0921
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,0921,Energy,21,9,43,0,0,0,0,2,10,0,0,0,0,9,43
1,0921,Industrials,75,23,31,3,4,3,4,5,7,5,7,5,7,23,31
2,0921,Health Care,63,18,29,4,6,4,6,10,16,5,8,5,8,18,29
3,0921,Financials,74,16,22,4,5,4,5,5,7,5,7,5,7,16,22
4,0921,Consumer Discretionary,58,11,19,1,2,2,3,8,14,2,3,3,5,11,19
5,0921,Communication Services,23,4,17,1,4,1,4,5,22,4,17,4,17,4,17
6,0921,Real Estate,29,5,17,1,3,1,3,4,14,1,3,1,3,5,17
7,0921,Information Technology,62,10,16,3,5,3,5,4,6,4,6,4,6,10,16
8,0921,Consumer Staples,36,4,11,1,3,1,3,1,3,0,0,0,0,4,11
9,0921,Materials,28,2,7,0,0,0,0,5,18,0,0,0,0,2,7
10,0921,Utilities,28,1,4,0,0,0,0,0,0,0,0,1,4,1,4

================================================================================
Imputation Summary - Period 1221
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,1221,Energy,21,9,43,0,0,0,0,2,10,0,0,0,0,9,43
1,1221,Industrials,74,22,30,3,4,3,4,4,5,4,5,4,5,22,30
2,1221,Health Care,63,18,29,4,6,4,6,10,16,5,8,5,8,18,29
3,1221,Financials,75,17,23,4,5,4,5,5,7,7,9,7,9,17,23
4,1221,Information Technology,64,12,19,2,3,2,3,3,5,6,9,6,9,12,19
5,1221,Consumer Discretionary,56,10,18,0,0,1,2,7,12,2,4,3,5,10,18
6,1221,Communication Services,23,4,17,1,4,1,4,4,17,4,17,4,17,4,17
7,1221,Real Estate,29,5,17,1,3,1,3,4,14,1,3,1,3,5,17
8,1221,Consumer Staples,36,4,11,1,3,1,3,2,6,0,0,0,0,4,11
9,1221,Materials,28,2,7,0,0,0,0,5,18,0,0,0,0,2,7
10,1221,Utilities,28,1,4,0,0,0,0,0,0,0,0,1,4,1,4

================================================================================
Imputation Summary - Period 0322
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,0322,Energy,21,9,43,0,0,0,0,1,5,0,0,0,0,9,43
1,0322,Health Care,64,19,30,3,5,3,5,8,12,6,9,6,9,19,30
2,0322,Industrials,76,22,29,1,1,1,1,3,4,4,5,4,5,22,29
3,0322,Financials,75,17,23,4,5,4,5,4,5,7,9,7,9,17,23
4,0322,Consumer Discretionary,55,10,18,0,0,0,0,5,9,2,4,3,5,10,18
5,0322,Communication Services,23,4,17,1,4,1,4,4,17,4,17,4,17,4,17
6,0322,Information Technology,63,11,17,0,0,0,0,2,3,5,8,5,8,11,17
7,0322,Real Estate,29,5,17,1,3,0,0,1,3,1,3,1,3,5,17
8,0322,Consumer Staples,36,4,11,1,3,1,3,2,6,0,0,0,0,4,11
9,0322,Materials,28,2,7,0,0,0,0,3,11,0,0,0,0,2,7
10,0322,Utilities,28,1,4,0,0,0,0,2,7,0,0,1,4,1,4

================================================================================
Imputation Summary - Period 0622
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,0622,Energy,21,9,43,0,0,0,0,1,5,0,0,0,0,9,43
1,0622,Health Care,63,19,30,1,2,1,2,7,11,6,10,6,10,19,30
2,0622,Industrials,76,22,29,1,1,1,1,3,4,4,5,4,5,22,29
3,0622,Real Estate,31,7,23,1,3,0,0,1,3,3,10,3,10,7,23
4,0622,Financials,74,16,22,4,5,4,5,4,5,6,8,6,8,16,22
5,0622,Consumer Discretionary,54,10,19,0,0,0,0,6,11,2,4,3,6,10,19
6,0622,Communication Services,23,4,17,1,4,1,4,2,9,4,17,4,17,4,17
7,0622,Information Technology,63,11,17,0,0,0,0,2,3,6,10,6,10,11,17
8,0622,Consumer Staples,37,5,14,1,3,1,3,2,5,1,3,1,3,5,14
9,0622,Materials,28,2,7,0,0,0,0,3,11,0,0,0,0,2,7
10,0622,Utilities,28,1,4,0,0,0,0,2,7,0,0,1,4,1,4

================================================================================
Imputation Summary - Period 0922
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,0922,Energy,21,9,43,0,0,0,0,1,5,0,0,0,0,9,43
1,0922,Health Care,63,19,30,1,2,1,2,7,11,6,10,6,10,19,30
2,0922,Industrials,76,22,29,2,3,2,3,5,7,4,5,4,5,22,29
3,0922,Real Estate,33,9,27,1,3,0,0,1,3,5,15,5,15,9,27
4,0922,Financials,74,16,22,4,5,4,5,3,4,6,8,6,8,16,22
5,0922,Consumer Discretionary,52,10,19,0,0,0,0,6,12,2,4,3,6,10,19
6,0922,Communication Services,23,4,17,1,4,1,4,1,4,4,17,4,17,4,17
7,0922,Information Technology,63,11,17,0,0,0,0,2,3,6,10,6,10,11,17
8,0922,Consumer Staples,37,5,14,2,5,2,5,3,8,1,3,1,3,5,14
9,0922,Materials,28,2,7,0,0,0,0,3,11,0,0,0,0,2,7
10,0922,Utilities,28,1,4,0,0,0,0,2,7,0,0,1,4,1,4

================================================================================
Imputation Summary - Period 1222
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,1222,Energy,23,11,48,0,0,0,0,1,4,2,9,2,9,11,48
1,1222,Health Care,62,18,29,1,2,1,2,7,11,5,8,5,8,18,29
2,1222,Industrials,74,21,28,1,1,1,1,4,5,4,5,4,5,21,28
3,1222,Real Estate,32,8,25,1,3,0,0,1,3,4,12,4,12,8,25
4,1222,Financials,75,17,23,5,7,5,7,4,5,7,9,7,9,17,23
5,1222,Consumer Discretionary,52,10,19,1,2,1,2,6,12,2,4,3,6,10,19
6,1222,Information Technology,63,11,17,1,2,1,2,4,6,6,10,6,10,11,17
7,1222,Communication Services,22,3,14,1,5,1,5,2,9,3,14,3,14,3,14
8,1222,Consumer Staples,37,5,14,3,8,3,8,3,8,1,3,1,3,5,14
9,1222,Materials,29,3,10,0,0,0,0,2,7,1,3,1,3,3,10
10,1222,Utilities,29,2,7,0,0,0,0,2,7,1,3,2,7,2,7

================================================================================
Imputation Summary - Period 0323
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,0323,Energy,23,11,48,2,9,2,9,2,9,2,9,2,9,11,48
1,0323,Health Care,63,19,30,1,2,1,2,5,8,6,10,6,10,19,30
2,0323,Industrials,74,21,28,1,1,1,1,2,3,4,5,4,5,21,28
3,0323,Real Estate,31,8,26,0,0,0,0,0,0,4,13,4,13,8,26
4,0323,Financials,73,16,22,3,4,3,4,4,5,6,8,6,8,16,22
5,0323,Consumer Discretionary,52,10,19,2,4,1,2,2,4,2,4,3,6,10,19
6,0323,Information Technology,64,12,19,1,2,1,2,3,5,7,11,7,11,12,19
7,0323,Consumer Staples,38,6,16,6,16,6,16,7,18,2,5,2,5,6,16
8,0323,Communication Services,21,3,14,1,5,1,5,2,10,3,14,3,14,3,14
9,0323,Materials,29,3,10,1,3,1,3,3,10,1,3,1,3,3,10
10,0323,Utilities,29,2,7,0,0,0,0,1,3,1,3,2,7,2,7

================================================================================
Imputation Summary - Period 0623
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,0623,Energy,23,11,48,2,9,2,9,2,9,2,9,2,9,11,48
1,0623,Health Care,64,20,31,1,2,1,2,4,6,7,11,7,11,20,31
2,0623,Industrials,75,22,29,2,3,2,3,3,4,5,7,5,7,22,29
3,0623,Real Estate,31,8,26,0,0,0,0,0,0,4,13,4,13,8,26
4,0623,Financials,72,16,22,2,3,2,3,3,4,6,8,6,8,16,22
5,0623,Information Technology,65,13,20,3,5,3,5,5,8,8,12,8,12,13,20
6,0623,Consumer Discretionary,52,10,19,3,6,2,4,2,4,2,4,3,6,10,19
7,0623,Consumer Staples,38,6,16,7,18,7,18,7,18,2,5,2,5,6,16
8,0623,Communication Services,20,2,10,1,5,1,5,2,10,2,10,2,10,2,10
9,0623,Materials,29,3,10,1,3,1,3,3,10,1,3,1,3,3,10
10,0623,Utilities,29,2,7,0,0,0,0,1,3,1,3,2,7,2,7

================================================================================
Imputation Summary - Period 0923
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,0923,Energy,23,11,48,2,9,2,9,2,9,2,9,2,9,11,48
1,0923,Health Care,64,20,31,2,3,2,3,4,6,7,11,7,11,20,31
2,0923,Industrials,75,22,29,3,4,3,4,3,4,5,7,5,7,22,29
3,0923,Real Estate,31,8,26,0,0,0,0,0,0,4,13,4,13,8,26
4,0923,Financials,72,17,24,2,3,2,3,3,4,7,10,7,10,17,24
5,0923,Information Technology,65,13,20,9,14,9,14,10,15,8,12,8,12,13,20
6,0923,Consumer Discretionary,52,10,19,3,6,3,6,3,6,3,6,3,6,10,19
7,0923,Consumer Staples,37,5,14,9,24,9,24,9,24,2,5,2,5,5,14
8,0923,Communication Services,20,2,10,2,10,2,10,3,15,2,10,2,10,2,10
9,0923,Materials,29,3,10,1,3,1,3,3,10,1,3,1,3,3,10
10,0923,Utilities,29,2,7,0,0,0,0,1,3,1,3,2,7,2,7

================================================================================
Imputation Summary - Period 1223
================================================================================

,Period,Sector,Number of Stocks,Missing Scope Count,Missing Scope (%),Filled Scope 1 Count,Filled Scope 1 %,Filled Scope 2 Count,Filled Scope 2 %,Filled Scope 3 Count,Filled Scope 3 %,Imputed Scope 1 Count,Imputed Scope 1 %,Imputed Scope 2 Count,Imputed Scope 2 %,Imputed Scope 3 Count,Imputed Scope 3 %
0,1223,Energy,23,11,48,2,9,2,9,2,9,2,9,2,9,11,48
1,1223,Industrials,77,25,32,4,5,4,5,5,6,8,10,8,10,25,32
2,1223,Health Care,63,19,30,3,5,3,5,4,6,6,10,6,10,19,30
3,1223,Real Estate,31,8,26,0,0,0,0,0,0,4,13,4,13,8,26
4,1223,Financials,72,17,24,4,6,4,6,4,6,7,10,7,10,17,24
5,1223,Consumer Discretionary,53,11,21,6,11,6,11,5,9,4,8,4,8,11,21
6,1223,Information Technology,64,13,20,15,23,15,23,16,25,8,12,8,12,13,20
7,1223,Consumer Staples,37,5,14,12,32,12,32,11,30,2,5,2,5,5,14
8,1223,Communication Services,19,2,11,2,11,2,11,2,11,2,11,2,11,2,11
9,1223,Materials,28,3,11,3,11,3,11,4,14,1,4,1,4,3,11
10,1223,Utilities,29,2,7,1,3,0,0,2,7,1,3,2,7,2,7

### Aggregate Imputation Summary (All Periods)

In [8]:
# Combine all imputation summaries
all_imputation = pd.concat(imputation_summaries, ignore_index=True)

# Build aggregation dict dynamically based on available columns
agg_dict = {
    'Number of Stocks': 'mean',
    'Imputed Scope 1 %': 'mean',
    'Imputed Scope 2 %': 'mean',
    'Imputed Scope 3 %': 'mean'
}

# Add filled percentages if they exist in the data
if 'Filled Scope 1 %' in all_imputation.columns:
    agg_dict['Filled Scope 1 %'] = 'mean'
if 'Filled Scope 2 %' in all_imputation.columns:
    agg_dict['Filled Scope 2 %'] = 'mean'
if 'Filled Scope 3 %' in all_imputation.columns:
    agg_dict['Filled Scope 3 %'] = 'mean'

# Aggregate by sector (averaging across periods)
agg_imputation = all_imputation.groupby('Sector').agg(agg_dict).reset_index()

# Round number of stocks to integer
agg_imputation['Number of Stocks'] = agg_imputation['Number of Stocks'].round(0).astype(int)

# Round percentages to integers
percentage_cols = [col for col in agg_imputation.columns if '%' in col]
agg_imputation[percentage_cols] = agg_imputation[percentage_cols].round(0).astype('Int64')
# Round and clean table
percentage_cols = [col for col in agg_imputation.columns if '%' in col]
agg_imputation[percentage_cols] = agg_imputation[percentage_cols].round(0).astype('Int64')

# Export LaTeX table body only
latex_body = agg_imputation.to_latex(
    index=False,
    escape=False,
    header=False,  # We'll handle headers manually in LaTeX
    float_format="%.0f"
)

with open("results/data_summaries/imputation_summary_body.tex", "w") as f:
    f.write(latex_body)

print("✓ Table body (no header) saved as results/imputation_summary_body.tex")

✓ Table body (no header) saved as results/imputation_summary_body.tex

In [9]:
agg_imputation.columns

Index(['Sector', 'Number of Stocks', 'Imputed Scope 1 %', 'Imputed Scope 2 %',
       'Imputed Scope 3 %', 'Filled Scope 1 %', 'Filled Scope 2 %',
       'Filled Scope 3 %'],
      dtype='object')

## 2. Sector Emissions Summary

### Individual Period Summaries

In [10]:
# Create emissions summary for each period
emissions_summaries = []

for period, df in all_periods_data.items():
    summary = sector_aggregates(df, period)
    emissions_summaries.append(summary)
    
    # Format for display
    summary_display = summary.copy()
    
    pct_cols = ["% Scope 1", "% Scope 2", "% Scope 3", "% Top 5 emitters", 
                "% Emissions in Top 20% Weight", "Sector Market Cap %"]
    summary_display[pct_cols] = summary_display[pct_cols].map(lambda x: f"{x:.1%}")
    
    round_cols = ["Avg Scope 1+2+3", "Avg Scope 1", "Avg Scope 2", "Avg Scope 3",
                  "Var Scope 1", "Var Scope 2", "Var Scope 3",
                  "Avg Carbon Intensity", "Aggregate Carbon Intensity"]
    summary_display[round_cols] = summary_display[round_cols].round(2)
    
    num_cols = ["Scope 1 sum","Scope 2 sum","Scope 3 sum","Scope 1+2+3 absolute"]
    summary_display[num_cols] = summary_display[num_cols].map(human_format)
    
    print(f"\n{'='*80}")
    print(f"Emissions Summary - Period {period}")
    print(f"{'='*80}")
    display(summary_display)

================================================================================
Emissions Summary - Period 0321
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,0321,Communication Services,4.7M,31.0M,101.0M,136.7M,3.4%,22.7%,73.9%,62.7%,0.0%,"6,213,388.82","212,846.93","1,407,733.10","4,592,808.78","296,163.26","1,862,387.71","6,067,106.86",0.20,0.12,9.1%
1,0321,Consumer Discretionary,36.2M,27.8M,1.3B,1.3B,2.7%,2.1%,95.2%,67.9%,0.0%,"22,840,767.62","624,727.83","478,487.21","21,737,552.57","1,939,659.72","901,982.33","59,062,763.79",1.12,0.78,9.1%
2,0321,Consumer Staples,46.2M,36.1M,1.3B,1.4B,3.3%,2.6%,94.2%,61.7%,13.8%,"39,189,817.92","1,282,626.35","1,002,379.00","36,904,812.57","2,556,044.10","1,684,409.29","60,140,521.27",0.83,0.75,9.1%
3,0321,Energy,342.5M,42.8M,3.3B,3.7B,9.2%,1.2%,89.6%,56.4%,0.0%,"161,246,323.73","14,892,685.57","1,858,785.74","144,494,852.42","22,636,333.69","2,240,399.62","141,657,941.93",5.09,3.50,9.1%
4,0321,Financials,17.8M,10.7M,1.6B,1.6B,1.1%,0.7%,98.2%,94.8%,0.1%,"21,964,245.18","240,866.46","144,655.28","21,578,723.45","1,881,847.26","612,019.14","119,947,032.81",1.83,0.87,9.1%
5,0321,Health Care,33.9M,24.8M,735.8M,794.5M,4.3%,3.1%,92.6%,73.9%,3.9%,"12,611,521.94","538,440.60","393,216.44","11,679,864.89","2,343,206.47","1,196,957.62","38,931,175.07",0.29,0.07,9.1%
6,0321,Industrials,201.9M,17.8M,3.1B,3.3B,6.1%,0.5%,93.3%,64.4%,1.9%,"44,448,922.20","2,728,982.62","240,966.77","41,478,972.81","6,253,934.42","300,367.78","144,957,536.94",3.97,2.43,9.1%
7,0321,Information Technology,31.1M,35.4M,742.2M,808.7M,3.8%,4.4%,91.8%,70.6%,0.0%,"12,837,049.00","493,092.01","562,396.47","11,781,560.52","2,137,141.08","1,230,627.90","42,066,223.41",3.03,0.24,9.1%
8,0321,Materials,144.4M,70.1M,466.9M,681.4M,21.2%,10.3%,68.5%,60.2%,8.7%,"25,237,292.11","5,348,298.74","2,596,797.15","17,292,196.23","7,139,269.01","4,486,483.25","24,771,228.76",1.64,1.59,9.1%
9,0321,Real Estate,8.2M,7.9M,88.9M,105.1M,7.8%,7.6%,84.6%,78.8%,4.5%,"3,624,632.39","284,067.76","273,661.10","3,066,903.53","1,146,888.37","545,873.09","7,428,285.94",0.98,0.82,9.1%
10,0321,Utilities,670.3M,28.0M,692.4M,1.4B,48.2%,2.0%,49.8%,37.1%,3.2%,"49,665,604.79","23,938,046.46","998,679.82","24,728,878.50","22,158,882.31","1,955,637.63","21,169,413.58",4.32,4.04,9.1%

================================================================================
Emissions Summary - Period 0621
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,0621,Communication Services,3.9M,27.3M,84.6M,115.8M,3.4%,23.6%,73.1%,62.6%,0.0%,"5,265,195.39","178,054.08","1,240,133.67","3,847,007.64","284,907.22","1,868,609.09","4,731,071.57",0.11,0.10,9.1%
1,0621,Consumer Discretionary,36.3M,28.6M,1.3B,1.4B,2.6%,2.0%,95.4%,65.1%,0.0%,"24,337,132.11","625,933.85","492,508.24","23,218,690.02","1,939,288.77","897,581.17","59,405,853.65",1.21,0.82,9.1%
2,0621,Consumer Staples,46.2M,36.1M,1.3B,1.3B,3.4%,2.7%,93.9%,60.5%,14.5%,"37,462,982.00","1,282,626.35","1,002,379.00","35,177,976.65","2,556,044.10","1,684,409.29","58,123,577.24",0.80,0.71,9.1%
3,0621,Energy,337.8M,42.2M,2.9B,3.2B,10.5%,1.3%,88.2%,54.6%,0.0%,"146,914,328.91","15,354,489.45","1,917,548.73","129,642,290.73","23,057,865.38","2,274,907.92","118,744,617.60",4.79,3.10,9.1%
4,0621,Financials,20.6M,13.1M,1.7B,1.7B,1.2%,0.8%,98.1%,96.3%,0.1%,"23,647,010.28","278,210.17","177,642.33","23,191,157.77","1,893,121.00","664,304.88","120,566,523.70",1.85,0.94,9.1%
5,0621,Health Care,15.0M,14.5M,471.2M,500.7M,3.0%,2.9%,94.1%,67.2%,6.3%,"7,948,353.25","237,809.46","230,776.86","7,479,766.93","923,062.12","523,765.34","29,226,948.72",0.22,0.06,9.1%
6,0621,Industrials,207.4M,19.6M,2.8B,3.0B,6.8%,0.6%,92.5%,67.3%,0.9%,"40,993,202.27","2,803,042.64","264,200.48","37,925,959.16","6,271,393.41","334,320.77","144,212,137.98",3.19,2.22,9.1%
7,0621,Information Technology,41.9M,37.6M,740.3M,819.7M,5.1%,4.6%,90.3%,66.8%,0.0%,"13,011,813.40","664,779.82","596,666.52","11,750,367.06","2,851,758.15","1,316,424.25","41,511,624.36",1.88,0.14,9.1%
8,0621,Materials,144.8M,70.7M,506.0M,721.5M,20.1%,9.8%,70.1%,56.8%,8.2%,"25,769,128.43","5,171,573.79","2,525,982.96","18,071,571.68","7,067,949.00","4,418,533.80","24,399,452.10",1.77,1.63,9.1%
9,0621,Real Estate,2.1M,8.6M,110.8M,121.4M,1.7%,7.1%,91.2%,80.3%,3.9%,"4,187,539.89","71,950.41","296,088.66","3,819,500.82","133,766.82","553,452.38","8,906,049.83",1.24,0.94,9.1%
10,0621,Utilities,670.3M,28.0M,657.6M,1.4B,49.4%,2.1%,48.5%,36.0%,3.3%,"48,423,426.21","23,938,046.46","998,679.82","23,486,699.93","22,158,882.31","1,955,637.63","19,569,299.76",4.27,3.94,9.1%

================================================================================
Emissions Summary - Period 0921
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,0921,Communication Services,4.9M,28.7M,91.0M,124.6M,3.9%,23.0%,73.0%,59.4%,0.0%,"5,418,312.70","213,711.77","1,247,154.14","3,957,446.79","276,496.57","1,817,669.56","4,715,107.95",0.20,0.11,9.1%
1,0921,Consumer Discretionary,36.5M,29.2M,1.2B,1.3B,2.8%,2.2%,95.0%,68.6%,0.0%,"22,605,120.20","629,716.35","503,450.78","21,471,953.07","1,938,329.79","900,649.38","59,091,113.58",1.04,0.76,9.1%
2,0921,Consumer Staples,46.2M,36.1M,1.2B,1.3B,3.5%,2.8%,93.7%,60.9%,14.9%,"36,403,907.61","1,282,626.35","1,002,379.00","34,118,902.27","2,556,044.10","1,684,409.29","57,312,974.00",0.78,0.68,9.1%
3,0921,Energy,337.6M,42.0M,3.0B,3.4B,9.9%,1.2%,88.9%,51.7%,0.0%,"162,735,033.59","16,077,211.05","1,999,018.81","144,658,803.74","23,370,551.37","2,297,964.97","114,960,374.31",7.09,3.30,9.1%
4,0921,Financials,7.8M,12.0M,1.6B,1.7B,0.5%,0.7%,98.8%,97.0%,0.1%,"22,376,019.50","104,851.94","161,531.57","22,109,635.99","779,859.20","594,017.45","120,534,552.46",1.70,0.89,9.1%
5,0921,Health Care,8.1M,11.3M,497.5M,516.9M,1.6%,2.2%,96.2%,56.7%,6.1%,"8,204,778.95","128,901.80","179,813.97","7,896,063.19","180,316.01","218,350.46","19,528,330.77",0.64,0.19,9.1%
6,0921,Industrials,201.9M,20.9M,2.8B,3.1B,6.6%,0.7%,92.7%,66.6%,3.0%,"40,876,203.73","2,692,155.04","278,253.03","37,905,795.67","6,215,611.07","356,238.79","143,211,114.94",3.24,2.24,9.1%
7,0921,Information Technology,49.9M,31.9M,487.2M,569.0M,8.8%,5.6%,85.6%,63.0%,0.0%,"9,177,597.29","804,349.21","514,827.95","7,858,420.14","5,019,012.42","1,139,440.61","28,544,340.58",0.46,0.09,9.1%
8,0921,Materials,144.8M,70.7M,489.8M,705.3M,20.5%,10.0%,69.4%,58.1%,8.4%,"25,189,301.68","5,171,573.79","2,525,982.96","17,491,744.93","7,067,949.00","4,418,533.80","24,323,596.46",1.68,1.58,9.1%
9,0921,Real Estate,3.4M,8.4M,89.9M,101.8M,3.4%,8.3%,88.3%,73.1%,4.7%,"3,508,694.32","118,517.31","290,984.86","3,099,192.15","281,360.30","549,408.16","6,819,502.45",0.92,0.79,9.1%
10,0921,Utilities,670.3M,28.9M,683.6M,1.4B,48.5%,2.1%,49.4%,36.7%,3.2%,"49,382,970.50","23,938,046.46","1,031,764.93","24,413,159.11","22,158,882.31","1,946,693.82","20,576,341.67",4.32,4.01,9.1%

================================================================================
Emissions Summary - Period 1221
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,1221,Communication Services,13.1M,29.5M,89.0M,131.6M,10.0%,22.4%,67.6%,55.8%,0.0%,"5,723,731.31","569,967.08","1,284,196.75","3,869,567.48","1,762,032.48","1,800,797.12","4,689,153.26",0.25,0.11,9.1%
1,1221,Consumer Discretionary,36.3M,28.4M,1.3B,1.4B,2.6%,2.1%,95.3%,65.8%,0.0%,"24,662,239.71","648,975.91","507,519.67","23,505,744.13","1,970,885.96","912,512.30","60,302,480.63",1.00,0.80,9.1%
2,1221,Consumer Staples,46.2M,36.1M,1.2B,1.3B,3.6%,2.8%,93.7%,61.4%,15.0%,"36,118,598.97","1,282,626.35","1,002,379.00","33,833,593.63","2,556,044.10","1,684,409.29","57,360,280.37",0.76,0.67,9.1%
3,1221,Energy,337.6M,42.0M,2.8B,3.2B,10.5%,1.3%,88.2%,55.7%,0.0%,"153,029,185.57","16,077,211.05","1,999,018.81","134,952,955.71","23,370,551.37","2,297,964.97","121,678,766.02",4.69,3.10,9.1%
4,1221,Financials,13.8M,11.6M,1.8B,1.8B,0.8%,0.7%,98.6%,95.5%,0.1%,"23,784,940.27","183,779.45","154,793.18","23,446,367.64","990,628.18","536,445.88","120,301,588.94",2.40,0.96,9.1%
5,1221,Health Care,9.2M,11.3M,322.0M,342.5M,2.7%,3.3%,94.0%,39.5%,9.1%,"5,436,313.92","145,702.59","180,139.62","5,110,471.70","195,925.03","223,584.46","7,918,142.78",0.43,0.13,9.1%
6,1221,Industrials,223.5M,25.4M,3.0B,3.3B,6.9%,0.8%,92.3%,63.0%,2.9%,"43,947,083.60","3,020,576.18","343,126.79","40,583,380.63","6,436,984.99","840,284.22","144,317,674.91",4.15,0.54,9.1%
7,1221,Information Technology,28.8M,33.7M,500.5M,563.0M,5.1%,6.0%,88.9%,58.3%,0.0%,"8,796,259.80","449,530.20","526,875.09","7,819,854.51","2,246,419.72","1,107,175.47","26,699,921.96",0.62,0.09,9.1%
8,1221,Materials,144.8M,70.7M,461.4M,677.0M,21.4%,10.4%,68.2%,60.6%,8.7%,"24,177,396.93","5,171,573.79","2,525,982.96","16,479,840.18","7,067,949.00","4,418,533.80","24,508,242.79",1.48,1.50,9.1%
9,1221,Real Estate,2.4M,8.3M,93.0M,103.8M,2.3%,8.0%,89.6%,78.9%,4.6%,"3,578,130.22","83,983.10","287,293.38","3,206,853.73","147,223.79","547,325.22","7,908,736.29",0.96,0.81,9.1%
10,1221,Utilities,670.3M,28.5M,692.3M,1.4B,48.2%,2.0%,49.8%,37.1%,3.2%,"49,679,567.18","23,938,046.46","1,016,213.64","24,725,307.07","22,158,882.31","1,948,945.13","21,162,060.17",4.28,4.03,9.1%

================================================================================
Emissions Summary - Period 0322
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,0322,Communication Services,17.6M,38.9M,379.6M,436.1M,4.0%,8.9%,87.0%,86.1%,0.0%,"18,961,385.68","764,898.46","1,691,498.15","16,504,989.07","2,732,334.87","2,455,982.13","58,499,320.18",0.18,0.07,9.1%
1,0322,Consumer Discretionary,44.6M,26.3M,1.3B,1.4B,3.2%,1.9%,94.9%,69.4%,0.0%,"25,484,414.87","810,587.04","477,286.45","24,196,541.39","2,258,637.35","876,891.43","67,336,259.12",0.77,0.75,9.1%
2,0322,Consumer Staples,46.6M,36.1M,1.4B,1.5B,3.2%,2.5%,94.3%,60.2%,12.2%,"40,429,534.72","1,293,403.43","1,002,800.45","38,133,330.83","2,563,531.85","1,711,759.12","61,905,406.65",0.77,0.71,9.1%
3,0322,Energy,327.1M,44.8M,3.1B,3.5B,9.4%,1.3%,89.3%,55.6%,0.0%,"165,609,223.09","15,578,087.19","2,134,062.24","147,897,073.66","22,719,013.48","2,532,132.70","129,055,417.33",3.88,2.29,9.1%
4,0322,Financials,18.9M,15.1M,634.6M,668.6M,2.8%,2.3%,94.9%,86.9%,3.8%,"8,914,017.00","251,390.37","201,603.09","8,461,023.54","1,829,320.43","937,215.09","42,546,200.48",0.96,0.17,9.1%
5,0322,Health Care,17.2M,12.8M,393.4M,423.4M,4.1%,3.0%,92.9%,46.0%,7.9%,"6,616,264.51","269,291.64","199,568.86","6,147,404.00","1,155,593.10","244,468.91","12,250,069.21",0.33,0.05,9.1%
6,0322,Industrials,224.9M,18.7M,3.5B,3.8B,5.9%,0.5%,93.6%,63.2%,2.1%,"49,753,948.62","2,959,615.45","246,181.48","46,548,151.69","7,225,122.57","295,253.17","147,353,810.33",3.64,0.74,9.1%
7,0322,Information Technology,60.1M,38.6M,677.4M,776.0M,7.7%,5.0%,87.3%,68.7%,0.0%,"12,318,009.06","953,495.11","612,305.68","10,752,208.28","6,444,129.43","1,547,914.10","46,560,433.30",0.69,0.16,9.1%
8,0322,Materials,142.4M,68.3M,470.7M,681.3M,20.9%,10.0%,69.1%,59.9%,9.3%,"24,333,624.05","5,085,633.86","2,438,385.08","16,809,605.12","6,957,153.23","4,310,354.92","23,765,634.93",1.27,1.37,9.1%
9,0322,Real Estate,32.5M,13.6M,316.4M,362.5M,9.0%,3.7%,87.3%,94.0%,1.5%,"12,501,472.95","1,120,752.48","468,739.10","10,911,981.37","5,632,894.89","995,196.13","46,858,294.20",0.33,0.29,9.1%
10,0322,Utilities,651.8M,29.1M,725.1M,1.4B,46.4%,2.1%,51.6%,37.3%,3.2%,"50,216,357.59","23,279,746.18","1,038,482.16","25,898,129.25","22,479,437.31","2,055,488.80","20,708,954.37",3.81,3.69,9.1%

================================================================================
Emissions Summary - Period 0622
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,0622,Communication Services,30.7M,36.8M,330.5M,398.0M,7.7%,9.2%,83.1%,82.1%,0.0%,"17,303,132.29","1,332,769.42","1,598,843.45","14,371,519.42","5,125,735.43","2,321,235.28","43,455,546.62",0.19,0.06,9.1%
1,0622,Consumer Discretionary,42.5M,25.6M,1.7B,1.7B,2.5%,1.5%,96.0%,73.4%,0.0%,"31,888,858.37","786,261.61","474,333.20","30,628,263.56","2,258,891.18","886,313.59","81,478,829.91",0.98,0.92,9.1%
2,0622,Consumer Staples,47.2M,36.4M,1.4B,1.4B,3.3%,2.5%,94.2%,61.0%,12.3%,"38,781,009.28","1,274,752.53","982,537.09","36,523,719.66","2,530,221.16","1,692,311.86","61,113,060.56",0.75,0.70,9.1%
3,0622,Energy,327.1M,44.8M,3.2B,3.5B,9.2%,1.3%,89.5%,55.7%,0.0%,"169,035,898.07","15,578,087.19","2,134,062.24","151,323,748.64","22,719,013.48","2,532,132.70","130,655,747.53",4.02,2.34,9.1%
4,0622,Financials,3.4M,10.3M,575.6M,589.3M,0.6%,1.8%,97.7%,85.1%,0.3%,"7,962,871.83","45,348.65","139,766.05","7,777,757.13","213,915.79","373,918.15","41,949,657.21",1.20,0.29,9.1%
5,0622,Health Care,39.3M,15.5M,877.8M,932.5M,4.2%,1.7%,94.1%,70.6%,3.6%,"14,802,113.41","623,839.48","245,463.53","13,932,810.39","3,855,647.17","636,121.97","48,360,808.49",1.73,0.23,9.1%
6,0622,Industrials,222.9M,19.5M,3.5B,3.7B,6.0%,0.5%,93.5%,63.9%,2.1%,"49,178,024.29","2,932,498.03","257,103.82","45,988,422.43","7,227,120.65","323,930.23","146,807,453.00",3.90,0.74,9.1%
7,0622,Information Technology,43.6M,40.4M,487.5M,571.4M,7.6%,7.1%,85.3%,61.0%,0.0%,"9,070,574.40","691,476.11","641,524.77","7,737,573.52","4,335,351.17","1,515,683.71","26,867,152.99",0.38,0.12,9.1%
8,0622,Materials,142.4M,68.3M,472.4M,683.1M,20.8%,10.0%,69.2%,59.8%,0.0%,"24,395,805.34","5,085,633.86","2,438,385.08","16,871,786.40","6,957,153.23","4,310,354.92","23,733,180.05",1.27,1.38,9.1%
9,0622,Real Estate,40.2M,15.3M,387.0M,442.6M,9.1%,3.5%,87.4%,91.1%,1.2%,"14,275,823.98","1,297,031.35","494,626.09","12,484,166.54","6,805,580.86","1,103,527.81","50,871,310.33",1.00,0.36,9.1%
10,0622,Utilities,651.8M,28.5M,725.1M,1.4B,46.4%,2.0%,51.6%,37.3%,3.2%,"50,195,189.06","23,279,746.18","1,017,313.62","25,898,129.25","22,479,437.31","2,059,375.38","20,708,954.37",3.80,3.69,9.1%

================================================================================
Emissions Summary - Period 0922
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,0922,Communication Services,44.0M,36.3M,374.2M,454.5M,9.7%,8.0%,82.3%,82.1%,0.0%,"19,761,488.89","1,913,386.24","1,578,615.32","16,269,487.33","8,209,542.69","2,294,102.93","51,777,496.06",0.36,0.07,9.1%
1,0922,Consumer Discretionary,42.2M,26.0M,1.4B,1.4B,2.9%,1.8%,95.3%,67.4%,0.0%,"27,853,975.32","810,650.31","499,252.57","26,544,072.44","2,298,760.43","897,572.76","69,405,367.30",0.97,0.78,9.1%
2,0922,Consumer Staples,46.6M,36.2M,1.4B,1.5B,3.1%,2.4%,94.5%,62.7%,11.8%,"40,643,034.48","1,258,816.69","978,861.50","38,405,356.30","2,536,416.65","1,694,087.02","63,410,650.96",0.75,0.72,9.1%
3,0922,Energy,327.1M,44.8M,3.1B,3.4B,9.5%,1.3%,89.2%,52.9%,0.0%,"164,206,709.11","15,578,087.19","2,134,062.24","146,494,559.68","22,719,013.48","2,532,132.70","118,984,263.64",4.27,2.27,9.1%
4,0922,Financials,37.5M,9.9M,754.5M,802.0M,4.7%,1.2%,94.1%,91.1%,31.3%,"10,837,592.51","506,659.96","134,315.55","10,196,617.00","3,619,071.87","469,149.44","48,372,149.39",1.11,0.39,9.1%
5,0922,Health Care,27.4M,20.8M,652.0M,700.3M,3.9%,3.0%,93.1%,64.9%,4.7%,"11,116,280.08","435,679.67","330,616.70","10,349,983.71","2,216,694.57","971,975.26","41,194,703.97",0.26,0.17,9.1%
6,0922,Industrials,230.9M,20.2M,3.3B,3.6B,6.5%,0.6%,93.0%,66.9%,2.7%,"47,007,179.69","3,038,692.11","265,612.33","43,702,875.25","7,236,324.55","340,906.68","147,180,398.86",3.16,0.70,9.1%
7,0922,Information Technology,48.7M,34.0M,610.9M,693.6M,7.0%,4.9%,88.1%,67.1%,0.0%,"11,008,982.20","772,674.79","539,360.79","9,696,946.62","4,980,712.94","1,282,936.69","41,178,655.19",0.42,0.14,9.1%
8,0922,Materials,142.4M,68.3M,472.5M,683.2M,20.8%,10.0%,69.2%,59.8%,9.3%,"24,398,703.30","5,085,633.86","2,438,385.08","16,874,684.37","6,957,153.23","4,310,354.92","23,735,300.89",1.27,1.38,9.1%
9,0922,Real Estate,34.5M,17.2M,360.1M,411.8M,8.4%,4.2%,87.4%,91.3%,2.2%,"12,478,236.04","1,045,453.03","521,321.18","10,911,461.83","4,742,078.58","1,085,130.29","49,362,734.61",0.62,0.33,9.1%
10,0922,Utilities,651.8M,30.0M,722.9M,1.4B,46.4%,2.1%,51.5%,37.2%,3.2%,"50,167,781.05","23,279,746.18","1,069,707.48","25,818,327.38","22,479,437.31","2,060,886.22","20,557,048.23",3.81,3.69,9.1%

================================================================================
Emissions Summary - Period 1222
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,1222,Communication Services,4.1M,30.1M,97.9M,132.1M,3.1%,22.8%,74.1%,62.5%,0.0%,"6,002,594.48","184,352.75","1,367,592.97","4,450,648.76","282,379.99","2,083,999.24","4,943,816.83",0.14,0.11,9.1%
1,1222,Consumer Discretionary,42.0M,25.4M,1.4B,1.5B,2.9%,1.7%,95.4%,68.0%,0.0%,"28,093,273.26","807,601.02","489,318.23","26,796,354.01","2,299,290.83","899,936.63","69,568,881.28",0.93,0.78,9.1%
2,1222,Consumer Staples,48.9M,36.3M,1.4B,1.5B,3.3%,2.4%,94.3%,59.7%,11.9%,"40,151,712.81","1,321,579.01","980,697.74","37,849,436.05","2,533,480.09","1,693,163.52","61,372,234.36",0.76,0.71,9.1%
3,1222,Energy,335.3M,46.3M,3.1B,3.5B,9.6%,1.3%,89.1%,52.3%,0.0%,"151,536,496.22","14,578,730.87","2,012,839.43","134,944,925.92","21,913,890.16","2,447,473.23","120,374,347.67",4.03,2.24,9.1%
4,1222,Financials,3.7M,12.3M,650.0M,665.9M,0.5%,1.8%,97.6%,86.5%,4.3%,"8,879,262.58","48,820.31","164,216.69","8,666,225.58","246,198.48","492,479.14","42,939,553.77",1.08,0.33,9.1%
5,1222,Health Care,10.7M,11.1M,430.0M,451.8M,2.4%,2.5%,95.2%,43.0%,7.4%,"7,286,752.86","172,451.50","178,665.57","6,935,635.78","369,836.26","229,902.50","12,509,292.03",0.42,0.15,9.1%
6,1222,Industrials,220.7M,17.7M,3.4B,3.6B,6.1%,0.5%,93.4%,66.5%,2.7%,"48,534,784.74","2,982,031.16","238,798.31","45,313,955.27","7,314,081.96","285,893.18","148,942,059.94",3.26,2.30,9.1%
7,1222,Information Technology,9.2M,36.8M,333.0M,378.9M,2.4%,9.7%,87.9%,32.4%,0.0%,"6,014,733.63","145,869.13","583,458.04","5,285,406.46","401,608.71","1,308,088.85","7,099,181.40",0.75,0.25,9.1%
8,1222,Materials,144.0M,68.5M,490.8M,703.3M,20.5%,9.7%,69.8%,58.1%,9.0%,"24,252,411.29","4,966,100.69","2,360,854.56","16,925,456.05","6,862,047.51","4,253,226.60","23,226,445.45",1.28,1.36,9.1%
9,1222,Real Estate,4.0M,16.2M,125.4M,145.5M,2.7%,11.1%,86.2%,74.9%,6.3%,"4,547,143.92","123,724.03","505,827.87","3,917,592.02","326,059.08","937,755.53","9,077,095.17",1.42,0.97,9.1%
10,1222,Utilities,685.5M,29.3M,738.9M,1.5B,47.2%,2.0%,50.8%,35.9%,3.1%,"50,129,472.98","23,639,065.28","1,011,398.50","25,479,009.20","22,159,015.62","2,023,712.52","20,269,154.41",3.75,3.61,9.1%

================================================================================
Emissions Summary - Period 0323
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,0323,Communication Services,9.3M,32.3M,174.8M,216.4M,4.3%,14.9%,80.8%,70.0%,0.0%,"10,302,654.33","440,855.90","1,538,988.90","8,322,809.52","1,186,191.83","2,396,549.89","12,835,691.55",0.41,0.02,9.1%
1,0323,Consumer Discretionary,43.5M,26.3M,1.5B,1.6B,2.7%,1.7%,95.6%,70.5%,0.0%,"30,559,651.30","836,728.65","506,416.48","29,216,506.17","2,444,983.56","914,804.21","75,561,233.40",0.74,0.79,9.1%
2,0323,Consumer Staples,47.1M,36.8M,1.6B,1.7B,2.8%,2.2%,95.0%,59.9%,10.5%,"44,198,415.52","1,240,118.42","968,895.60","41,989,401.51","2,379,103.88","1,669,889.15","66,684,843.29",2.10,0.76,9.1%
3,0323,Energy,347.1M,49.3M,3.6B,3.9B,8.8%,1.2%,90.0%,52.7%,0.0%,"171,600,178.26","15,090,356.41","2,142,224.02","154,367,597.83","21,283,357.71","2,500,148.86","138,985,732.80",5.97,3.04,9.1%
4,0323,Financials,2.0M,13.1M,1.2B,1.2B,0.2%,1.1%,98.7%,94.4%,14.2%,"16,399,417.52","27,608.36","179,396.06","16,192,413.10","78,636.60","856,474.87","77,367,024.18",2.20,0.14,9.1%
5,0323,Health Care,14.1M,14.9M,336.3M,365.3M,3.8%,4.1%,92.1%,46.5%,7.3%,"5,798,831.17","223,143.12","237,140.88","5,338,547.17","590,633.95","464,339.10","9,508,189.93",0.47,0.12,9.1%
6,0323,Industrials,252.1M,20.7M,3.3B,3.6B,7.1%,0.6%,92.3%,65.9%,2.4%,"48,105,980.96","3,407,028.76","279,883.28","44,419,068.92","8,222,006.98","378,402.90","150,871,281.46",2.82,2.21,9.1%
7,0323,Information Technology,12.6M,33.4M,312.2M,358.2M,3.5%,9.3%,87.1%,35.9%,0.0%,"5,597,636.76","197,628.04","522,314.21","4,877,694.51","528,856.77","1,245,812.34","7,016,093.40",0.67,0.23,9.1%
8,0323,Materials,141.3M,68.2M,482.6M,692.0M,20.4%,9.9%,69.7%,58.4%,9.1%,"23,862,222.14","4,870,738.75","2,351,086.18","16,640,397.21","6,842,236.64","4,247,268.21","23,053,617.41",1.52,1.46,9.1%
9,0323,Real Estate,18.0M,10.6M,171.6M,200.2M,9.0%,5.3%,85.7%,82.9%,2.7%,"6,457,174.75","581,040.56","341,217.97","5,534,916.21","2,592,556.97","748,597.28","13,139,097.95",1.78,1.27,9.1%
10,0323,Utilities,602.7M,21.6M,762.9M,1.4B,43.4%,1.6%,55.0%,36.3%,3.2%,"47,834,318.04","20,782,457.87","743,983.85","26,307,876.31","20,322,914.86","1,436,338.43","22,624,062.68",3.60,3.51,9.1%

================================================================================
Emissions Summary - Period 0623
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,0623,Communication Services,3.9M,30.3M,95.4M,129.6M,3.0%,23.4%,73.6%,65.0%,0.0%,"6,478,992.73","193,553.60","1,517,265.00","4,768,174.13","268,419.35","2,449,735.78","5,416,660.37",0.12,0.01,9.1%
1,0623,Consumer Discretionary,43.8M,26.5M,1.6B,1.6B,2.7%,1.6%,95.7%,69.2%,0.0%,"31,234,523.03","841,906.31","508,851.38","29,883,765.34","2,443,829.69","915,822.90","75,708,287.59",0.76,0.81,9.1%
2,0623,Consumer Staples,46.2M,36.4M,1.4B,1.4B,3.2%,2.5%,94.3%,59.8%,12.3%,"37,971,479.31","1,216,197.55","957,333.46","35,797,948.30","2,381,876.57","1,671,522.27","60,033,292.73",0.79,0.66,9.1%
3,0623,Energy,335.3M,48.7M,3.4B,3.8B,8.7%,1.3%,90.0%,50.7%,0.0%,"166,693,324.04","14,578,203.02","2,118,823.15","149,996,297.87","21,450,947.52","2,513,059.22","129,882,946.82",6.37,2.95,9.1%
4,0623,Financials,55.9M,12.9M,1.5B,1.5B,3.7%,0.8%,95.5%,91.1%,27.5%,"21,166,848.94","776,679.27","179,674.66","20,210,495.01","6,127,878.35","805,088.64","86,004,263.25",2.42,0.60,9.1%
5,0623,Health Care,10.0M,12.1M,336.2M,358.3M,2.8%,3.4%,93.8%,41.8%,7.4%,"5,598,245.15","155,879.70","188,671.74","5,253,693.71","263,025.66","238,453.17","8,360,102.79",0.42,0.12,9.1%
6,0623,Industrials,234.7M,17.2M,3.2B,3.5B,6.8%,0.5%,92.7%,67.5%,2.5%,"46,326,644.41","3,129,905.00","229,618.16","42,967,121.24","8,164,245.10","271,975.41","150,098,919.18",2.49,2.15,9.1%
7,0623,Information Technology,15.3M,35.9M,306.9M,358.1M,4.3%,10.0%,85.7%,36.5%,0.0%,"5,508,801.14","235,450.53","552,026.32","4,721,324.29","644,962.08","1,242,560.81","7,042,957.27",0.57,0.23,9.1%
8,0623,Materials,141.7M,67.9M,469.2M,678.8M,20.9%,10.0%,69.1%,59.5%,0.0%,"23,406,510.07","4,885,041.96","2,341,129.56","16,180,338.55","6,832,295.82","4,252,559.04","23,140,175.28",1.49,1.44,9.1%
9,0623,Real Estate,5.2M,13.1M,149.7M,168.1M,3.1%,7.8%,89.1%,80.0%,3.2%,"5,421,933.65","168,197.82","423,384.13","4,830,351.70","392,157.25","890,506.23","12,056,970.70",1.63,1.06,9.1%
10,0623,Utilities,603.0M,22.9M,707.6M,1.3B,45.2%,1.7%,53.1%,35.7%,3.4%,"45,984,107.62","20,794,463.77","789,892.64","24,399,751.21","20,320,142.63","1,492,192.73","20,043,516.11",3.54,3.37,9.1%

================================================================================
Emissions Summary - Period 0923
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,0923,Communication Services,5.0M,30.8M,99.7M,135.5M,3.7%,22.7%,73.6%,63.2%,0.0%,"6,774,174.81","251,583.96","1,537,789.85","4,984,801.00","437,747.06","2,449,682.77","5,287,537.06",0.19,0.02,9.1%
1,0923,Consumer Discretionary,46.7M,27.2M,1.6B,1.7B,2.8%,1.6%,95.6%,67.3%,0.0%,"32,591,985.56","898,753.26","522,459.90","31,170,772.40","2,471,076.05","926,976.63","75,822,712.46",0.86,0.84,9.1%
2,0923,Consumer Staples,66.7M,37.0M,1.4B,1.5B,4.5%,2.5%,93.0%,58.2%,11.9%,"40,084,974.21","1,803,537.29","999,794.56","37,281,642.36","3,438,988.15","1,685,250.73","60,170,913.05",1.00,0.67,9.1%
3,0923,Energy,336.0M,49.1M,3.4B,3.8B,8.8%,1.3%,89.9%,50.3%,0.0%,"165,620,170.21","14,609,890.59","2,134,650.41","148,875,629.22","21,431,106.44","2,505,187.00","127,682,747.09",6.54,2.93,9.1%
4,0923,Financials,16.5M,10.7M,1.7B,1.7B,1.0%,0.6%,98.4%,90.3%,11.2%,"24,064,323.46","228,717.85","149,008.08","23,686,597.53","1,809,375.61","521,663.25","89,457,182.05",2.67,0.69,9.1%
5,0923,Health Care,19.5M,11.7M,321.2M,352.4M,5.5%,3.3%,91.1%,39.5%,7.0%,"5,506,098.16","304,790.37","182,673.27","5,018,634.53","1,164,296.49","219,094.93","7,897,427.39",0.44,0.11,9.1%
6,0923,Industrials,245.5M,17.4M,3.4B,3.7B,6.7%,0.5%,92.8%,64.0%,1.3%,"48,846,524.77","3,273,015.72","232,306.62","45,341,202.43","8,180,582.10","271,317.22","151,500,018.43",2.82,2.27,9.1%
7,0923,Information Technology,28.3M,35.4M,381.2M,444.8M,6.4%,8.0%,85.7%,43.1%,0.0%,"6,843,844.10","434,618.97","544,160.31","5,865,064.83","1,791,038.52","1,236,487.30","11,086,165.80",0.65,0.28,9.1%
8,0923,Materials,141.2M,68.1M,450.9M,660.2M,21.4%,10.3%,68.3%,61.2%,0.0%,"22,765,884.79","4,870,525.34","2,347,143.56","15,548,215.90","6,842,391.42","4,249,283.15","23,249,928.35",1.39,1.40,9.1%
9,0923,Real Estate,9.4M,11.0M,180.0M,200.4M,4.7%,5.5%,89.8%,81.5%,1.8%,"6,465,025.84","302,096.95","356,061.36","5,806,867.54","1,069,006.36","746,273.46","16,167,274.71",1.72,1.27,9.1%
10,0923,Utilities,590.2M,21.1M,672.1M,1.3B,46.0%,1.6%,52.4%,36.8%,3.5%,"44,255,907.83","20,350,669.94","728,792.82","23,176,445.07","20,557,971.44","1,436,891.17","19,598,081.18",3.46,3.25,9.1%

================================================================================
Emissions Summary - Period 1223
================================================================================

,Period,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %
0,1223,Communication Services,3.5M,29.7M,85.6M,118.8M,2.9%,25.0%,72.0%,70.6%,0.0%,"6,251,928.14","182,559.46","1,565,649.21","4,503,719.47","271,167.69","2,507,258.89","5,220,050.10",0.12,0.10,9.1%
1,1223,Consumer Discretionary,44.6M,28.6M,1.5B,1.6B,2.8%,1.8%,95.5%,69.7%,0.0%,"30,354,137.59","840,572.24","539,059.18","28,974,506.16","2,420,992.88","977,735.85","74,896,908.02",0.81,0.79,9.1%
2,1223,Consumer Staples,60.5M,36.7M,1.4B,1.5B,3.9%,2.4%,93.7%,59.2%,11.5%,"41,534,499.02","1,635,932.67","991,786.99","38,906,779.36","3,298,887.23","1,684,560.40","61,520,956.15",0.86,0.69,9.1%
3,1223,Energy,339.9M,53.5M,2.9B,3.3B,10.3%,1.6%,88.1%,52.2%,0.0%,"143,273,545.71","14,776,244.85","2,325,826.11","126,171,474.76","21,331,496.59","2,473,775.33","114,843,798.22",6.16,2.53,9.1%
4,1223,Financials,16.7M,9.2M,1.4B,1.4B,1.2%,0.7%,98.1%,91.8%,22.0%,"19,128,049.49","232,250.58","127,206.21","18,768,592.70","1,758,510.01","385,502.43","82,219,440.48",2.31,0.54,9.1%
5,1223,Health Care,9.1M,11.3M,357.2M,377.5M,2.4%,3.0%,94.6%,44.0%,6.5%,"5,992,283.95","143,928.07","178,836.66","5,669,519.22","223,149.21","228,618.28","9,412,829.55",0.32,0.12,9.1%
6,1223,Industrials,231.4M,23.6M,3.3B,3.5B,6.6%,0.7%,92.8%,66.6%,1.8%,"45,714,118.23","3,005,105.93","307,032.55","42,401,979.75","8,047,615.27","422,287.62","148,199,848.56",2.52,2.13,9.1%
7,1223,Information Technology,11.2M,31.7M,364.5M,407.4M,2.7%,7.8%,89.5%,36.3%,0.0%,"6,365,382.80","174,711.31","496,036.06","5,694,635.43","435,214.32","1,209,701.10","8,703,878.62",0.82,0.25,9.1%
8,1223,Materials,141.3M,68.0M,558.1M,767.4M,18.4%,8.9%,72.7%,64.6%,0.0%,"27,408,745.61","5,046,905.28","2,429,801.40","19,932,038.93","6,900,636.70","4,303,796.57","30,975,787.17",2.00,0.04,9.1%
9,1223,Real Estate,5.3M,10.9M,122.7M,139.0M,3.8%,7.9%,88.3%,71.3%,3.9%,"4,483,136.76","171,451.37","352,701.91","3,958,983.48","436,307.83","750,802.30","7,748,509.90",1.12,0.88,9.1%
10,1223,Utilities,587.0M,21.1M,642.3M,1.3B,46.9%,1.7%,51.4%,37.8%,3.6%,"43,116,546.83","20,242,084.46","727,883.06","22,146,579.31","20,657,888.43","1,437,618.42","19,162,503.22",3.43,3.16,9.1%

### Aggregate Emissions Summary (All Periods)

In [11]:
# Combine all emissions summaries
all_emissions = pd.concat(emissions_summaries, ignore_index=True)

# Aggregate by sector (averaging across periods)
agg_emissions = all_emissions.groupby('Sector').agg({
    'Scope 1 sum': 'mean',
    'Scope 2 sum': 'mean',
    'Scope 3 sum': 'mean',
    'Scope 1+2+3 absolute': 'mean',
    '% Scope 1': 'mean',
    '% Scope 2': 'mean',
    '% Scope 3': 'mean',
    '% Top 5 emitters': 'mean',
    '% Emissions in Top 20% Weight': 'mean',
    'Avg Scope 1+2+3': 'mean',
    'Avg Scope 1': 'mean',
    'Avg Scope 2': 'mean',
    'Avg Scope 3': 'mean',
    'Var Scope 1': 'mean',
    'Var Scope 2': 'mean',
    'Var Scope 3': 'mean',
    'Avg Carbon Intensity': 'mean',
    'Aggregate Carbon Intensity': 'mean',
    'Sector Market Cap %': 'mean'
}).reset_index()

# Load sector volatility data and merge with emissions summary
volatility_file = Path("data/benchmark_returns_volatility/sector_annualized_volatility_2021_2023.xlsx")

if volatility_file.exists():
    volatility_df = pd.read_excel(volatility_file, index_col=0)
    
    # The volatility file has sector names as index and a single column with volatility values
    # Convert to a DataFrame with 'Sector' and 'Annualized Volatility' columns
    volatility_df = volatility_df.reset_index()
    volatility_df.columns = ['Sector', 'Annualized Volatility']
    
    # Merge with aggregate emissions
    agg_emissions = agg_emissions.merge(volatility_df, on='Sector', how='left')
    
    print(f"\n✓ Successfully merged volatility data")
    print(f"  Added 'Annualized Volatility' column to aggregate emissions summary")
else:
    print(f"\n⚠ Volatility file not found at: {volatility_file}")
    print("  Run 'benchmark_replication.py' first to generate volatility data")

# Sort by total emissions
agg_emissions = agg_emissions.sort_values('Scope 1+2+3 absolute', ascending=False).reset_index(drop=True)

# Format for display
agg_emissions_display = agg_emissions.copy()

pct_cols = ["% Scope 1", "% Scope 2", "% Scope 3", "% Top 5 emitters", 
            "% Emissions in Top 20% Weight", "Sector Market Cap %"]
agg_emissions_display[pct_cols] = agg_emissions_display[pct_cols].map(lambda x: f"{x:.1%}")

round_cols = ["Avg Scope 1+2+3", "Avg Scope 1", "Avg Scope 2", "Avg Scope 3",
              "Var Scope 1", "Var Scope 2", "Var Scope 3",
              "Avg Carbon Intensity", "Aggregate Carbon Intensity"]
agg_emissions_display[round_cols] = agg_emissions_display[round_cols].round(2)

# Format Annualized Volatility if it exists
if 'Annualized Volatility' in agg_emissions_display.columns:
    agg_emissions_display['Annualized Volatility'] = agg_emissions_display['Annualized Volatility'].map(lambda x: f"{x:.2%}")

num_cols = ["Scope 1 sum","Scope 2 sum","Scope 3 sum","Scope 1+2+3 absolute"]
agg_emissions_display[num_cols] = agg_emissions_display[num_cols].map(human_format)

print(f"\n{'='*80}")
print(f"AGGREGATE EMISSIONS SUMMARY (Average across {len(PERIODS)} periods)")
print(f"{'='*80}")
display(agg_emissions_display)

✓ Successfully merged volatility data
  Added 'Annualized Volatility' column to aggregate emissions summary

================================================================================
AGGREGATE EMISSIONS SUMMARY (Average across 12 periods)
================================================================================

,Sector,Scope 1 sum,Scope 2 sum,Scope 3 sum,Scope 1+2+3 absolute,% Scope 1,% Scope 2,% Scope 3,% Top 5 emitters,% Emissions in Top 20% Weight,Avg Scope 1+2+3,Avg Scope 1,Avg Scope 2,Avg Scope 3,Var Scope 1,Var Scope 2,Var Scope 3,Avg Carbon Intensity,Aggregate Carbon Intensity,Sector Market Cap %,Annualized Volatility
0,Energy,335.9M,45.9M,3.2B,3.5B,9.5%,1.3%,89.2%,53.4%,0.0%,"160,125,034.71","15,230,773.70","2,075,910.16","142,818,350.85","22,333,595.06","2,428,939.93","125,625,558.41",5.24,2.80,9.1%,28.47%
1,Industrials,224.8M,19.9M,3.2B,3.5B,6.5%,0.6%,92.9%,65.5%,2.2%,"46,144,384.79","2,997,720.72","265,256.97","42,881,407.10","7,232,918.59","368,431.50","147,304,354.54",3.26,1.72,9.1%,17.25%
2,Consumer Discretionary,41.3M,27.1M,1.4B,1.5B,2.8%,1.8%,95.4%,68.5%,0.0%,"27,708,839.91","763,534.53","499,911.94","26,445,393.44","2,223,718.85","909,064.93","68,970,057.56",0.93,0.80,9.1%,25.68%
3,Consumer Staples,49.5M,36.3M,1.4B,1.4B,3.4%,2.5%,94.1%,60.4%,12.7%,"39,414,163.82","1,347,903.58","989,351.95","37,076,908.29","2,657,223.50","1,686,681.77","60,762,392.55",0.91,0.70,9.1%,13.61%
4,Utilities,642.1M,26.4M,701.9M,1.4B,46.8%,1.9%,51.2%,36.8%,3.3%,"48,254,270.81","22,616,680.48","931,066.03","24,706,524.30","21,674,314.51","1,817,451.49","20,512,449.15",3.87,3.67,9.1%,18.32%
5,Financials,17.9M,11.8M,1.3B,1.3B,1.5%,1.1%,97.4%,91.7%,9.6%,"17,427,049.88","243,765.28","159,484.06","17,023,800.54","1,769,030.23","604,023.20","82,683,764.06",1.81,0.57,9.1%,19.37%
6,Materials,143.0M,69.0M,482.6M,694.5M,20.6%,9.9%,69.4%,59.7%,5.9%,"24,599,752.15","5,063,269.47","2,443,326.38","17,093,156.30","6,957,848.65","4,331,606.92","24,406,882.47",1.51,1.34,9.1%,19.54%
7,Information Technology,31.7M,35.4M,495.3M,562.4M,5.4%,6.9%,87.8%,53.3%,0.0%,"8,879,223.63","501,472.94","557,662.69","7,820,088.01","2,651,350.44","1,281,904.43","24,531,385.69",0.91,0.18,9.1%,25.21%
8,Health Care,17.8M,14.3M,477.6M,509.7M,3.4%,2.9%,93.7%,52.8%,6.4%,"8,076,486.45","281,654.83","227,132.01","7,567,699.60","1,123,448.84","449,636.00","20,424,835.06",0.50,0.13,9.1%,14.27%
9,Communication Services,12.0M,31.8M,166.9M,210.8M,4.9%,18.9%,76.2%,68.5%,0.0%,"9,538,081.63","536,544.97","1,464,621.71","7,536,914.95","1,761,093.20","2,192,334.20","17,303,213.20",0.21,0.07,9.1%,24.08%
10,Real Estate,13.8M,11.8M,183.0M,208.5M,5.4%,6.7%,87.9%,81.5%,3.4%,"6,794,078.72","447,355.51","384,325.63","5,962,397.58","1,975,490.09","787,820.66","19,695,321.84",1.14,0.82,9.1%,20.46%

In [14]:
volatility_df['Annualized Volatility'].mean()

0.2056809907474607

In [12]:


def compute_sector_structural_metrics(all_periods_data):
    """
    Computes the structural metrics for each sector across periods:
      1a. HHI of benchmark weights
      1b. Largest benchmark weight
      2a. Top 10% carbon intensity weight share
      2b. Weight needed to reach 50% of sector carbon footprint
      2c. Coefficient of variation (CV) of carbon intensity
      4.  Number of constituents

    Returns:
        DataFrame with sectors as rows and metrics averaged across periods.
    """

    results = []

    for period, df in all_periods_data.items():

        # Clean:
        df = df.copy()
        df["Carbon Intensity"] = df["Carbon Intensity"].astype(float)
        df["weight_in_sector"] = df["weight_in_sector"].astype(float)

        # Group by sector
        for sector, sdf in df.groupby("GICS Sector"):

            weights = sdf["weight_in_sector"].values
            carb = sdf["Carbon Intensity"].values

            # -----------------------------
            # 1a. HHI
            # -----------------------------
            hhi = np.sum(weights**2)

            # -----------------------------
            # 1b. Largest constituent weight
            # -----------------------------
            largest_weight = weights.max()

            # -----------------------------
            # 2a. Top 10% most carbon intensive weight share
            # -----------------------------
            n_top = max(1, int(len(sdf) * 0.10))
            sdf_sorted = sdf.sort_values("Carbon Intensity", ascending=False)
            top10_weight = sdf_sorted.head(n_top)["weight_in_sector"].sum()

            # -----------------------------
            # 2b. Weight needed to reach 50% of sector carbon footprint
            # -----------------------------
            sdf_sorted["carbon_contrib"] = sdf_sorted["weight_in_sector"] * sdf_sorted["Carbon Intensity"]
            total_carbon = sdf_sorted["carbon_contrib"].sum()

            sdf_sorted["cum_carbon"] = sdf_sorted["carbon_contrib"].cumsum()
            cutoff_row = sdf_sorted[sdf_sorted["cum_carbon"] >= 0.5 * total_carbon].iloc[0]
            weight_to_half_carbon = sdf_sorted.loc[:cutoff_row.name]["weight_in_sector"].sum()

            # -----------------------------
            # 2c. Coefficient of variation of carbon intensity
            # -----------------------------
            if carb.mean() > 0:
                cv_carbon = carb.std() / carb.mean()
            else:
                cv_carbon = np.nan

            # -----------------------------
            # 4. Number of constituents
            # -----------------------------
            n_const = len(sdf)

            results.append({
                "Period": period,
                "Sector": sector,
                "HHI": hhi,
                "Largest Weight": largest_weight,
                "Top10% CI Weight": top10_weight,
                "Weight to 50% Carbon": weight_to_half_carbon,
                "CV Carbon Intensity": cv_carbon,
                "Num Constituents": n_const
            })

    # Convert to DataFrame
    results_df = pd.DataFrame(results)

    # Average across periods
    aggregated = (
        results_df
        .groupby("Sector")
        .mean(numeric_only=True)
        .reset_index()
        .sort_values("Sector")
    )

    return aggregated

In [13]:
metrics_table = compute_sector_structural_metrics(all_periods_data)
print(metrics_table)

vol_2123 = pd.read_excel(
    "data/benchmark_returns_volatility/sector_annualized_volatility_2021_2023.xlsx",
    header=0
)

# Clean: ensure column names are correct
vol_2123.columns = ["Sector", "annual_vol_21_23"]

# Merge on "Sector"
metrics_table = metrics_table.merge(
    vol_2123,
    on="Sector",
    how="left"
)

print(metrics_table)

                    Sector  HHI  Largest Weight  Top10% CI Weight  \
0   Communication Services 0.23            0.42              0.02
1   Consumer Discretionary 0.14            0.31              0.06
2         Consumer Staples 0.07            0.14              0.17
3                   Energy 0.13            0.26              0.03
4               Financials 0.04            0.09              0.04
5              Health Care 0.04            0.10              0.04
6              Industrials 0.03            0.07              0.06
7   Information Technology 0.15            0.27              0.02
8                Materials 0.07            0.19              0.06
9              Real Estate 0.05            0.12              0.07
10               Utilities 0.07            0.17              0.04

    Weight to 50% Carbon  CV Carbon Intensity  Num Constituents
0                   0.35                 1.87             21.75
1                   0.13                 1.38             54.33
2                   0.26                 1.11             36.75
3                   0.26                 0.82             22.08
4                   0.01                 5.59             73.67
5                   0.10                 3.12             63.17
6                   0.04                 2.36             75.00
7                   0.06                 3.11             63.50
8                   0.35                 1.25             28.25
9                   0.08                 2.54             30.42
10                  0.38                 0.38             28.42
                    Sector  HHI  Largest Weight  Top10% CI Weight  \
0   Communication Services 0.23            0.42              0.02
1   Consumer Discretionary 0.14            0.31              0.06
2         Consumer Staples 0.07            0.14              0.17
3                   Energy 0.13            0.26              0.03
4               Financials 0.04            0.09              0.04
5              Health Care 0.04            0.10              0.04
6              Industrials 0.03            0.07              0.06
7   Information Technology 0.15            0.27              0.02
8                Materials 0.07            0.19              0.06
9              Real Estate 0.05            0.12              0.07
10               Utilities 0.07            0.17              0.04

    Weight to 50% Carbon  CV Carbon Intensity  Num Constituents  \
0                   0.35                 1.87             21.75
1                   0.13                 1.38             54.33
2                   0.26                 1.11             36.75
3                   0.26                 0.82             22.08
4                   0.01                 5.59             73.67
5                   0.10                 3.12             63.17
6                   0.04                 2.36             75.00
7                   0.06                 3.11             63.50
8                   0.35                 1.25             28.25
9                   0.08                 2.54             30.42
10                  0.38                 0.38             28.42

    annual_vol_21_23
0               0.24
1               0.26
2               0.14
3               0.28
4               0.19
5               0.14
6               0.17
7               0.25
8               0.20
9               0.20
10              0.18

In [14]:
metrics_table = metrics_table.rename(columns={
    "HHI": "HHI (Benchmark Concentration)",
    "Largest Weight": "Largest Constituent Weight",
    "Top10% CI Weight": "Weight in Top 10% CI Firms",
    "Weight to 50% Carbon": "Weight to 50% Carbon Contribution",
    "CV Carbon Intensity": "CV Carbon Intensity",
    "Num Constituents": "Number of Constituents",
    "annual_vol_21_23": "Annualized Volatility 2021–2023"
})

In [16]:
metrics_table.loc[:, ['Weight in Top 10% CI Firms', 'Weight to 50% Carbon Contribution', 'Annualized Volatility 2021–2023']]

,Weight in Top 10% CI Firms,Weight to 50% Carbon Contribution,Annualized Volatility 2021–2023
0,0.02,0.35,0.24
1,0.06,0.13,0.26
2,0.17,0.26,0.14
3,0.03,0.26,0.28
4,0.04,0.01,0.19
5,0.04,0.10,0.14
6,0.06,0.04,0.17
7,0.02,0.06,0.25
8,0.06,0.35,0.20
9,0.07,0.08,0.20
10,0.04,0.38,0.18

HHii is more connected to flesibility and sensitivity (inverted), so the higher the concentration less flexibility in theory
and same for large weight and number of constituents

Flexibility is more connected with:
- HHI -> the higher the worse the flexibility
- Largest weight -> the higher the worse the flexibility
- Number of constituents

In [34]:
dri = pd.read_excel("results/DRI/decarbonization_readiness_index.xlsx")

In [36]:
metrics_table = pd.merge(metrics_table, dri, how= 'left', on = 'Sector')

In [37]:
metrics_table.sort_values(by = 'HHI (Benchmark Concentration)', ascending=False)[['Sector', 'HHI (Benchmark Concentration)', 'Flex_norm']] # true but xception for financials that has many stocks

                    Sector  HHI (Benchmark Concentration)  Flex_norm
0   Communication Services                           0.23       0.09
7   Information Technology                           0.15       0.25
1   Consumer Discretionary                           0.14       0.00
3                   Energy                           0.13       0.04
8                Materials                           0.07       0.24
2         Consumer Staples                           0.07       0.19
10               Utilities                           0.07       0.41
9              Real Estate                           0.05       0.72
5              Health Care                           0.04       0.25
4               Financials                           0.04       1.00
6              Industrials                           0.03       0.54

In [ ]:
metrics_table.sort_values(by = 'Largest Constituent Weight', ascending=False) # true, exception for financials but has many stocks

,Sector,HHI (Benchmark Concentration),Largest Constituent Weight,Weight in Top 10% CI Firms,Weight to 50% Carbon Contribution,CV Carbon Intensity,Number of Constituents,Annualized Volatility 2021–2023
0,Communication Services,0.23,0.42,0.02,0.35,1.87,21.75,0.24
1,Consumer Discretionary,0.14,0.31,0.06,0.13,1.38,54.33,0.26
7,Information Technology,0.15,0.27,0.02,0.06,3.11,63.50,0.25
3,Energy,0.13,0.26,0.03,0.26,0.82,22.08,0.28
8,Materials,0.07,0.19,0.06,0.35,1.25,28.25,0.20
10,Utilities,0.07,0.17,0.04,0.38,0.38,28.42,0.18
2,Consumer Staples,0.07,0.14,0.17,0.26,1.11,36.75,0.14
9,Real Estate,0.05,0.12,0.07,0.08,2.54,30.42,0.20
5,Health Care,0.04,0.10,0.04,0.10,3.12,63.17,0.14
4,Financials,0.04,0.09,0.04,0.01,5.59,73.67,0.19
6,Industrials,0.03,0.07,0.06,0.04,2.36,75.00,0.17

Room for maneuver is more strongly associated with top 10% CI weight, with weight to 50% carbon contribution and with CV of carbon intensity. So if:
- the top **10% carbon intensity** has a **lower weight** in the portfolio that's **better**
- if the **weight to 50% carbon contribution** is **lower** that's also a **good** thing
- while for the **coefficient of variation of carbon intensity the higher the better** because then there is large spread between lowest and highest carbon intensities, i.e. many opportunities to reweight toward cleaner firms

In [27]:
metrics_table.sort_values(by = 'Weight in Top 10% CI Firms', ascending=True) # doesn't hold

,Sector,HHI (Benchmark Concentration),Largest Constituent Weight,Weight in Top 10% CI Firms,Weight to 50% Carbon Contribution,CV Carbon Intensity,Number of Constituents,Annualized Volatility 2021–2023
0,Communication Services,0.23,0.42,0.02,0.35,1.87,21.75,0.24
7,Information Technology,0.15,0.27,0.02,0.06,3.11,63.50,0.25
3,Energy,0.13,0.26,0.03,0.26,0.82,22.08,0.28
5,Health Care,0.04,0.10,0.04,0.10,3.12,63.17,0.14
4,Financials,0.04,0.09,0.04,0.01,5.59,73.67,0.19
10,Utilities,0.07,0.17,0.04,0.38,0.38,28.42,0.18
8,Materials,0.07,0.19,0.06,0.35,1.25,28.25,0.20
6,Industrials,0.03,0.07,0.06,0.04,2.36,75.00,0.17
1,Consumer Discretionary,0.14,0.31,0.06,0.13,1.38,54.33,0.26
9,Real Estate,0.05,0.12,0.07,0.08,2.54,30.42,0.20
2,Consumer Staples,0.07,0.14,0.17,0.26,1.11,36.75,0.14

In [28]:
metrics_table.sort_values(by = 'Weight to 50% Carbon Contribution', ascending=True) # doesn't hold

,Sector,HHI (Benchmark Concentration),Largest Constituent Weight,Weight in Top 10% CI Firms,Weight to 50% Carbon Contribution,CV Carbon Intensity,Number of Constituents,Annualized Volatility 2021–2023
4,Financials,0.04,0.09,0.04,0.01,5.59,73.67,0.19
6,Industrials,0.03,0.07,0.06,0.04,2.36,75.00,0.17
7,Information Technology,0.15,0.27,0.02,0.06,3.11,63.50,0.25
9,Real Estate,0.05,0.12,0.07,0.08,2.54,30.42,0.20
5,Health Care,0.04,0.10,0.04,0.10,3.12,63.17,0.14
1,Consumer Discretionary,0.14,0.31,0.06,0.13,1.38,54.33,0.26
3,Energy,0.13,0.26,0.03,0.26,0.82,22.08,0.28
2,Consumer Staples,0.07,0.14,0.17,0.26,1.11,36.75,0.14
0,Communication Services,0.23,0.42,0.02,0.35,1.87,21.75,0.24
8,Materials,0.07,0.19,0.06,0.35,1.25,28.25,0.20
10,Utilities,0.07,0.17,0.04,0.38,0.38,28.42,0.18

In [30]:
metrics_table.sort_values(by = 'CV Carbon Intensity', ascending=False) # doesn't hold

,Sector,HHI (Benchmark Concentration),Largest Constituent Weight,Weight in Top 10% CI Firms,Weight to 50% Carbon Contribution,CV Carbon Intensity,Number of Constituents,Annualized Volatility 2021–2023
4,Financials,0.04,0.09,0.04,0.01,5.59,73.67,0.19
5,Health Care,0.04,0.10,0.04,0.10,3.12,63.17,0.14
7,Information Technology,0.15,0.27,0.02,0.06,3.11,63.50,0.25
9,Real Estate,0.05,0.12,0.07,0.08,2.54,30.42,0.20
6,Industrials,0.03,0.07,0.06,0.04,2.36,75.00,0.17
0,Communication Services,0.23,0.42,0.02,0.35,1.87,21.75,0.24
1,Consumer Discretionary,0.14,0.31,0.06,0.13,1.38,54.33,0.26
8,Materials,0.07,0.19,0.06,0.35,1.25,28.25,0.20
2,Consumer Staples,0.07,0.14,0.17,0.26,1.11,36.75,0.14
3,Energy,0.13,0.26,0.03,0.26,0.82,22.08,0.28
10,Utilities,0.07,0.17,0.04,0.38,0.38,28.42,0.18

In [32]:
metrics_table.sort_values(by = 'Annualized Volatility 2021–2023', ascending=False) # doesn't hold

,Sector,HHI (Benchmark Concentration),Largest Constituent Weight,Weight in Top 10% CI Firms,Weight to 50% Carbon Contribution,CV Carbon Intensity,Number of Constituents,Annualized Volatility 2021–2023
3,Energy,0.13,0.26,0.03,0.26,0.82,22.08,0.28
1,Consumer Discretionary,0.14,0.31,0.06,0.13,1.38,54.33,0.26
7,Information Technology,0.15,0.27,0.02,0.06,3.11,63.50,0.25
0,Communication Services,0.23,0.42,0.02,0.35,1.87,21.75,0.24
9,Real Estate,0.05,0.12,0.07,0.08,2.54,30.42,0.20
8,Materials,0.07,0.19,0.06,0.35,1.25,28.25,0.20
4,Financials,0.04,0.09,0.04,0.01,5.59,73.67,0.19
10,Utilities,0.07,0.17,0.04,0.38,0.38,28.42,0.18
6,Industrials,0.03,0.07,0.06,0.04,2.36,75.00,0.17
5,Health Care,0.04,0.10,0.04,0.10,3.12,63.17,0.14
2,Consumer Staples,0.07,0.14,0.17,0.26,1.11,36.75,0.14

## Save Results

In [12]:
# Create results directory
RESULTS_DIR = Path("results/data_summaries/")
RESULTS_DIR.mkdir(exist_ok=True)

# Save aggregate summaries
output_file = RESULTS_DIR / "sector_summaries_aggregate.xlsx"

with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
    # Save aggregate imputation summary
    agg_imputation.to_excel(writer, sheet_name='Imputation Summary', index=False)
    
    # Save aggregate emissions summary (raw numbers, not formatted)
    agg_emissions.to_excel(writer, sheet_name='Emissions Summary', index=False)
    
    # Save all periods imputation data
    all_imputation.to_excel(writer, sheet_name='All Periods Imputation', index=False)
    
    # Save all periods emissions data
    all_emissions.to_excel(writer, sheet_name='All Periods Emissions', index=False)
    
    # Save filled counts by period
    if 'filled_counts_df' in locals():
        filled_counts_df.to_excel(writer, sheet_name='Filled Counts by Period', index=False)

print(f"\nResults saved to: {output_file}")
print(f"  - Imputation Summary (aggregate)")
print(f"  - Emissions Summary (aggregate)")
print(f"  - All Periods Imputation (detailed)")
print(f"  - All Periods Emissions (detailed)")
if 'filled_counts_df' in locals():
    print(f"  - Filled Counts by Period")

Results saved to: results/data_summaries/sector_summaries_aggregate.xlsx
  - Imputation Summary (aggregate)
  - Emissions Summary (aggregate)
  - All Periods Imputation (detailed)
  - All Periods Emissions (detailed)